export function slugifyTerm(term) {
  return term.toLowerCase()
    .replace(/ą/g,'a').replace(/ć/g,'c').replace(/ę/g,'e')
    .replace(/ł/g,'l').replace(/ń/g,'n').replace(/ó/g,'o')
    .replace(/ś/g,'s').replace(/ź/g,'z').replace(/ż/g,'z')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export const DICTIONARY_TERMS = [
  // === CNM / POLIAMORIA ===
  { term: 'CNM (Consensual Non-Monogamy)', slug: 'cnm', definition: 'CNM to parasol, pod którym mieści się wszystko co nie jest klasyczną monogamią — ale dzieje się za wiedzą i zgodą wszystkich zaangażowanych. Innymi słowy: nie chodzi o zdradę, chodzi o wybranie innego modelu. Obejmuje polyamorię, swinging, otwarte związki, DADT i dziesiątki innych konfiguracji. Klucz to słowo "consensual" — wszyscy wiedzą, wszyscy się zgadzają, nikt nie jest zaskoczony. CNM praktykuje szacunkowo kilka procent dorosłych, choć wielu robi to po cichu, bez etykiety. Nie ma jednego "właściwego" sposobu na CNM — to jak pizza, każdy układa swoje składniki. Wbrew obawom, badania pokazują że ludzie w CNM mają podobny poziom satysfakcji ze związku co monogamiści. Podstawowe narzędzie: komunikacja. Dużo komunikacji. Prawdopodobnie więcej niż myślisz.', category: 'CNM / Poliamoria', examples: ['CNM to szerokie pojęcie — klucz to zgoda i komunikacja, nie konkretna forma związku.'] },
  { term: 'ENM (Ethical Non-Monogamy)', slug: 'enm', definition: 'ENM to synonim CNM — używane zamiennie, zależnie od tego kogo pytasz. Słowo "ethical" (etyczna) ma podkreślać że to nie jest tylko "rób co chcesz" — tu chodzi o uczciwość, przejrzystość i szacunek dla wszystkich osób w układzie. Ktoś wymyślił ENM żeby odciąć się od skojarzeń z niewiernością i chaosem. Jeśli CNM brzmi technicznie, ENM brzmi bardziej jak deklaracja wartości. W praktyce: te same rzeczy, inna etykieta na opakowaniu. Część osób woli "CNM" bo brzmi neutralnie, inni wolą "ENM" bo podkreśla intencje. W rozmowie możesz używać obu — nikt Cię nie poprawi.', category: 'CNM / Poliamoria', examples: ['ENM kładzie nacisk na uczciwość — dlatego "ethical" w nazwie.'] },
  { term: 'Poliamoria', slug: 'poliamoria', definition: 'Poliamoria to zdolność i chęć kochania więcej niż jednej osoby jednocześnie — i robienie tego otwarcie, za wiedzą wszystkich. Różni się od swingingu tym, że chodzi nie tylko o seks, ale też o emocje, przywiązanie, może wspólne życie. Nazwa pochodzi z greckiego "poly" (wiele) i łacińskiego "amor" (miłość) — lingwistyczny miszmasz, który jakoś się przyjął. Wbrew popularnemu mitowi, polyamoria nie oznacza że kochasz każdego tak samo — każda relacja jest inna, tak jak są różni ludzie. Często słyszysz "ale jak możesz kochać więcej niż jedną osobę?" — to jak pytać rodzica czy mniej kocha drugie dziecko bo urodziło się pierwsze. Miłość nie jest pizzą do podziału na kawałki. Polyamoria wymaga dużo komunikacji, samoświadomości i czasu — to nie jest łatwiejsze niż monogamia, po prostu inne.', category: 'CNM / Poliamoria', examples: ['Ania jest w związku z Markiem od 5 lat i od roku spotyka się też z Kasią. Wszyscy o tym wiedzą i się wspierają.'] },
  { term: 'Otwarty związek', slug: 'otwarty-zwiazek', definition: 'W otwartym związku para ma główną relację emocjonalną i romantyczną tylko ze sobą — ale seks z innymi osobami jest ok. Emocje zostają w domu, ciało może podróżować. To jedna z najbardziej popularnych form CNM, często pierwsza próba dla par które chcą "otworzyć" związek. Kluczowe pytanie do ustalenia na początku: co dokładnie jest "otwarte"? Czy mogą być randki? Czy nocowanie u kogoś innego jest ok? Czy w twoim mieście, czy tylko w delegacji? Każda para ustala własne zasady — nie ma jednego wzorca. Częsty błąd: para otwiera związek licząc że rozwiąże to inne problemy. Nie rozwiązuje — raczej amplifikuje to co już jest. Jeśli związek jest zdrowy, może być fajną przygodą.', category: 'CNM / Poliamoria', examples: ['W otwartym związku można mieć przygody, ale romantyczne zaangażowanie zostaje w parze.'] },
  { term: 'Polyfidelity / Poliwierność', slug: 'polyfidelity', definition: 'Polyfidelity to zamknięta grupa ludzi — na przykład trójka lub czwórka — którzy są razem nawzajem i tylko ze sobą. Brzmi paradoksalnie: "wierna poliamoria"? Tak, dokładnie. Myśl o tym jak o monogamii, tylko rozszerzonej na więcej osób. Wszyscy w grupie wiedzą o wszystkich, wszyscy są ze wszystkimi, nikt nie szuka niczego "na zewnątrz" bez rozmowy z resztą. To jedna z bardziej stabilnych konfiguracji CNM — jeśli dynamika grupowa działa. Wymaga dużo wzajemnego zaufania i jasnych rozmów o tym co się dzieje gdy ktoś chce poszerzyć grupę. Popularne wśród ludzi którzy chcą bliskości i zaangażowania, ale nie są przekonani do klasycznej pary. Trójki i czwórki polyfidelity istnieją od dekad — po prostu rzadko o tym mówią głośno.', category: 'CNM / Poliamoria', examples: ['Adam, Ewa i Tomek są razem od 3 lat. To ich zamknięta trójka.'] },
  { term: 'Compersion', slug: 'compersion', definition: 'Compersion to uczucie radości i ciepła które czujesz widząc że Twój partner jest szczęśliwy z kimś innym. Często opisywane jako "przeciwieństwo zazdrości" — choć to nie do końca precyzyjne, bo można mieć jednocześnie i jedno, i drugie. Słowo nie istnieje w słowniku polskim ani angielskim — wymyśliła je społeczność poly w latach 90. i się przyjęło. Brzmi abstrakcyjnie dopóki tego nie poczujesz — wtedy nagle rozumiesz dlaczego people in poly są tak podekscytowani tym słowem. Compersion nie jest obowiązkowe ani "dowodem" że jesteś "dobry w poly" — niektórzy nigdy tego nie czują i to też jest ok. Jeśli Twój partner wraca ze szczęśliwą miną z randki i Ty czujesz się z tym dobrze albo wręcz cieszysz — właśnie to jest compersion. Bywa mylone z brakiem uczuć, ale to coś zupełnie innego: to aktywna, pozytywna emocja, nie obojętność.', category: 'CNM / Poliamoria', examples: ['Widzisz że Twoja dziewczyna świetnie się bawi na randce z kimś innym i czujesz radość zamiast zazdrości — to compersion.'] },
  { term: 'NRE (New Relationship Energy)', slug: 'nre', definition: 'NRE to ta intensywna, rozedrgana faza na początku nowej relacji — kiedy non-stop myślisz o tej osobie, wszystko wydaje się idealne, seks jest niesamowity i masz wrażenie że wreszcie rozumiesz o co chodzi w życiu. To biochemia: dopamina, oksytocyna i adrenalina robią swoje. Trwa zwykle od kilku miesięcy do półtora roku, potem opada — i to jest normalne, nie oznacza że związek umiera. W CNM NRE jest szczególnie ważne bo gdy partner wchodzi w nową relację, jego energia i czas mogą się przesunąć w tamtą stronę. Dla osób z boku może to boleć — nawet jeśli rozumiesz to racjonalnie, emocje mają swoje zdanie. Dobra praktyka: mów partnerowi gdy czujesz że NRE go "wciąga" kosztem Waszego czasu. Warto też pamiętać że osoby w NRE mają tendencję do podejmowania impulsywnych decyzji — wstrzymaj się z dużymi zobowiązaniami dopóki mgła nie opadnie.', category: 'CNM / Poliamoria', examples: ['W fazie NRE wszystko wydaje się idealne — warto zachować zdrowy rozsądek i rozmawiać z partnerem.'] },
  { term: 'Metamour', slug: 'metamour', definition: 'Metamour to partner Twojego partnera — osoba z którą nie jesteś w relacji romantycznej, ale jesteście połączeni przez kogoś wspólnego. Jeśli jesteś z Anią, a Ania jest też z Tomkiem — Tomek jest Twoim metamourem. Nie musicie być przyjaciółmi, nie musicie się lubić, choć miło gdy tak jest. Relacja z metamourem może być wszystkim: od "hej, cześć" przez SMS po prawdziwa przyjaźń i wspólne obiady. W kitchen table poly metamours się znają i lubią. W parallel poly możesz nawet nie znać ich imienia. Wiele osób odkrywa że metamourowie są całkiem fajnymi ludźmi — w końcu mają dobry gust, skoro wybrali tego samego partnera co Ty. Słowo pochodzi ze środowiska poly anglojęzycznego i nie ma dobrego polskiego odpowiednika — "partner partnera" brzmi jak łamigłówka, więc metamour zostaje.', category: 'CNM / Poliamoria', examples: ['Mój metamour i ja lubimy wspólnie gotować, choć nie jesteśmy parą.'] },
  { term: 'Polycule', slug: 'polycule', definition: 'Polycule to cała sieć osób połączonych relacjami poliamorycznymi — bezpośrednio lub pośrednio. Nazwa pochodzi od "molecule" — tak jak atomy w cząsteczce, ludzie są połączeni różnymi wiązaniami. Ty jesteś z Anią, Ania jest z Tomkiem, Tomek jest z Kasią i Piotrem — to jest jeden polycule. Konfiguracje bywają skomplikowane jak diagram chemiczny i niektórzy naprawdę rysują schematy żeby się nie pogubić. Polycule może być małe (trzy osoby) albo rozrastać się do kilkunastu gdy relacje się splatają przez lata. Nie wszyscy w polycule muszą się znać ani lubić — ale zazwyczaj jest jakaś świadomość że "należymy do tej samej sieci". W środowisku poly słyszysz czasem "mój polycule" z prawdziwą dumą — to jak powiedzieć "moja rodzina", tyle że z wyboru.', category: 'CNM / Poliamoria', examples: ['Ty jesteś z Anią, Ania jest z Tomkiem, Tomek jest z Kasią — to jest Twój polycule.'] },
  { term: 'Unicorn', slug: 'unicorn', definition: 'Unicorn to biseksualna kobieta gotowa dołączyć do istniejącej pary hetero (mężczyzna + kobieta) jako "trzecia" — i być z obojgiem jednocześnie, na ich warunkach. Nazwa pochodzi stąd że taka osoba jest rzadka jak jednorożec — i słusznie, bo oczekiwania par bywają nierealistyczne. Para często szuka kogoś kto będzie "pasował idealnie" do obu, nie będzie miał własnych potrzeb emocjonalnych, nie zagrozi ich związkowi i zniknie gdy para zdecyduje. Unicorny z kolei są pełnoprawnymi ludźmi z własnym życiem, uczuciami i oczekiwaniami — co często zaskakuje pary szukające "dodatku". Termin bywa używany przez same te kobiety z humorem i dystansem, czasem z rozmysłem jako self-identifier. Jeśli szukasz unicorna — zanim wyślesz kolejne ogłoszenie, zastanów się co możesz zaoferować tej osobie, nie tylko czego oczekujesz.', category: 'CNM / Poliamoria', examples: ['Wiele par szuka unicorna, ale warto pamiętać o podmiotowości takiej osoby.'] },
  { term: 'Unicorn Hunting', slug: 'unicorn-hunting', definition: 'Unicorn hunting to aktywne poszukiwanie przez parę biseksualnej kobiety do trójkąta — i niestety często w sposób który nie uwzględnia jej jako pełnoprawnego uczestnika. Red flags w ogłoszeniach: "must love us both equally", "no drama", "nie możecie spotykać się osobno", "nasze zasady". Para zakłada że trzecia osoba dopasuje się do ich dynamiki, nie będzie chciała niczego "za dużo" i zniknie gdy nie będzie już potrzebna. W efekcie unicorn hunting jest krytykowane w społeczności poly jako traktowanie drugiego człowieka jak zabawki, nie partnera. Nie oznacza to że trójki nie mogą działać — mogą i działają świetnie. Różnica jest prosta: jeśli trzecia osoba ma takie same prawa i głos jak reszta, to nie jest hunting. Jeśli ma się dopasować do Waszego gotowego scenariusza — to jest.', category: 'CNM / Poliamoria', examples: ['Unicorn hunting bywa problematyczne gdy para traktuje trzecią osobę jako dodatek, nie równorzędnego partnera.'] },
  { term: 'Primary / Secondary Partner', slug: 'primary-secondary-partner', definition: 'W modelu hierarchicznym poly partnerzy mają różne "poziomy" — primary to partner główny (najczęściej mieszkacie razem, macie wspólne finanse, decydujecie razem o ważnych sprawach), secondary to partner drugorzędny, który ma mniej "przywilejów". Brzmi zimno i trochę jest. Zwolennicy mówią że to uczciwe i przejrzyste — każdy wie na czym stoi. Krytycy mówią że uprzedmiotawia secondary partnerów, sprowadzając ich do roli "drugorzędnych". W praktyce wiele osób używa tych słów żeby opisać realia swojego życia, nie żeby kogoś umniejszyć. Alternatywą jest model non-hierarchiczny gdzie nie ma formalnej hierarchii — każda relacja jest ceniona za siebie. Jeśli rozważasz hierarchical poly, warto porozmawiać z potential secondary partnerem o tym czego się spodziewać — zanim ktoś się zakoccha i odkryje że ma być "na drugim miejscu".', category: 'CNM / Poliamoria', examples: ['W hierarchical poly partner primary często ma prawo weta przy nowych relacjach.'] },
  { term: 'Nesting Partner', slug: 'nesting-partner', definition: 'Nesting partner to osoba z którą dzielisz przestrzeń życiową — mieszkacie razem, macie wspólną łazienkę, kłócicie się o zmywarkę. "Nesting" od angielskiego "nest" — gniazdo. To ważne rozróżnienie w poly, bo zamieszkanie razem nie musi oznaczać że ta relacja jest "ważniejsza" od innych. Można mieć nesting partnera i jednocześnie równie głęboką relację z kimś kto mieszka po drugiej stronie miasta. Wspólne mieszkanie to praktyczna konfiguracja, nie hierarchia emocjonalna — przynajmniej w teorii. W praktyce bycie nesting partnerem często wiąże się z większą ilością czasu razem i naturalnym "uprzywilejowaniem" logistycznym. Warto być tego świadomym i rozmawiać z innymi partnerami o tym jak to wpływa na ich poczucie miejsca w Twoim życiu.', category: 'CNM / Poliamoria', examples: ['Mieszkam z Tomkiem (nesting partner), ale mój związek z Asią jest równie ważny emocjonalnie.'] },
  { term: 'Anchor Partner', slug: 'anchor-partner', definition: 'Anchor partner to osoba która jest Twoim głównym emocjonalnym punktem odniesienia — Twoja kotwica. Niekoniecznie mieszkacie razem, niekoniecznie jesteście "primary" w formalnym sensie, ale to do tej osoby wracasz gdy coś jest trudne, z nią świętuje sukcesy i przy niej czujesz się najbardziej sobą. Termin pochodzi ze środowisk non-hierarchical poly jako alternatywa dla "primary" — mniej korporacyjna, bardziej emocjonalna. Anchor partner to nie tytuł który się nadaje, to rola którą ktoś naturalnie zajmuje w Twoim życiu. Możesz mieć więcej niż jedną taką osobę, albo żadnej — i to też jest ok w ramach solo poly. Dobrze jest powiedzieć komuś wprost że jest Twoją kotwicą — ludzie lubią wiedzieć że są ważni.', category: 'CNM / Poliamoria', examples: ['Ona jest moim anchor partner — zawsze do niej wracam po trudnych chwilach.'] },
  { term: 'Kitchen Table Poly', slug: 'kitchen-table-poly', definition: 'Kitchen table poly to styl poliamorii gdzie wszyscy partnerzy i metamourowie znają się, lubią i mogą wspólnie usiąść przy stole kuchennym na kawę i pogadać — bez niezręczności, bez napięcia. Wyobraź sobie: Ty, Twój partner, jego inna partnerka i jej mąż — i wszyscy dobrze się bawicie na wspólnym obiedzie. Nazwa jest trochę idealistyczna, ale całkiem dobrze opisuje intencję: budowanie sieci relacji gdzie wszyscy są ze sobą w jakimś kontakcie. Kitchen table poly nie oznacza że wszyscy muszą być przyjaciółmi na zawsze — chodzi o atmosferę ciepła i otwartości zamiast dyplomatycznego dystansu. Przeciwieństwem jest parallel poly gdzie każda relacja jest osobna i partnerzy nie mają ze sobą kontaktu. Który styl pasuje — to kwestia temperamentu, nie wartości. Oba są ok.', category: 'CNM / Poliamoria', examples: ['W naszej sieci praktykujemy kitchen table poly — wszyscy razem obchodzimy urodziny.'] },
  { term: 'Parallel Poly', slug: 'parallel-poly', definition: 'Styl poliamorii gdzie partnerzy wiedzą o sobie nawzajem, ale nie mają bezpośrednich relacji. Każdy związek jest osobny.', category: 'CNM / Poliamoria', examples: ['Ona i jej mąż preferują parallel poly — każde ma swoje osobne życie.'] },
  { term: 'Solo Poly', slug: 'solo-poly', definition: 'Styl poliamorii gdzie osoba priorytetyzuje własną autonomię i nie szuka "main partner". Każda relacja stoi sama za siebie.', category: 'CNM / Poliamoria', examples: ['Jako solo poly, nie szukam głównego partnera — cenię niezależność i każdy związek traktuję osobno.'] },
  { term: 'Hierarchical Poly', slug: 'hierarchical-poly', definition: 'Model poliamorii z hierarchią: partner główny (primary) ma więcej praw niż partnerzy drugorzędni. Kontrowersyjny — wielu uważa to za niesprawiedliwe.', category: 'CNM / Poliamoria', examples: ['W hierarchical poly partner primary może mieć prawo weta przy nowych relacjach.'] },
  { term: 'Non-hierarchical Poly', slug: 'non-hierarchical-poly', definition: 'Model poliamorii bez formalnej hierarchii — każda relacja jest ceniona za siebie i ma własną wartość.', category: 'CNM / Poliamoria', examples: ['Preferujemy non-hierarchical poly — każdy związek ma swoją własną wartość.'] },
  { term: 'Relationship Anarchy', slug: 'relationship-anarchy', definition: 'Filozofia odrzucająca sztywne kategorie relacji. Nie ma różnicy między "romantyką" a "przyjaźnią". Każdy związek jest definiowany indywidualnie bez presji etykiet.', category: 'CNM / Poliamoria', examples: ['Relationship anarchy pozwala tworzyć relacje bez presji etykiet i oczekiwań społecznych.'] },
  { term: 'Veto Power', slug: 'veto-power', definition: 'Prawo partnera do zawetowania innego związku. Bardzo kontrowersyjne w poly community — jedni mówią "potrzebne dla bezpieczeństwa", inni "nieetyczne bo kontrolujesz autonomię partnera".', category: 'CNM / Poliamoria', examples: ['Zrezygnowaliśmy z veto — wolimy rozmawiać o uczuciach niż używać uprawnień.'] },
  { term: 'Triad', slug: 'triad', definition: 'Związek trzech osób gdzie każda para w grupie jest ze sobą w relacji. Wszyscy są ze wszystkimi.', category: 'CNM / Poliamoria', examples: ['Tworzą triad od trzech lat i wszystkim wychodzi świetnie.'] },
  { term: 'Quad', slug: 'quad', definition: 'Związek czterech osób, zazwyczaj dwie pary, gdzie wszyscy są ze sobą połączeni. Rzadkie i wymagające dużo komunikacji.', category: 'CNM / Poliamoria', examples: ['Quad to cztery osoby tworzące sieć wzajemnych relacji.'] },
  { term: 'V-relationship', slug: 'v-relationship', definition: 'Jedna osoba (hinge) ma dwóch partnerów którzy nie są ze sobą. Konfiguracja jak litera "V" — hinge jest na środku.', category: 'CNM / Poliamoria', examples: ['Ty jesteś z Anią i z Tomkiem, ale Ania i Tomek nie są ze sobą — to V-relationship, Ty jesteś hinge.'] },
  { term: 'Hinge', slug: 'hinge', definition: 'W V-relationship, osoba która łączy dwóch partnerów którzy nie są ze sobą. Dosłownie: "zawias".', category: 'CNM / Poliamoria', examples: ['Jako hinge masz odpowiedzialność wobec obojga partnerów — wymagające, ale satysfakcjonujące.'] },
  { term: 'Cowboy / Cowgirl', slug: 'cowboy-cowgirl', definition: 'Osoba która celowo datuje kogoś poly z zamiarem "zabrania ich ze sceny" — żeby zostali mono tylko z nią/nim.', category: 'CNM / Poliamoria', examples: ['Spotykasz się z kimś kto wie że jesteś poly, ale mówi "zakochasz się i zostawisz innych".'] },
  { term: 'Couple Privilege', slug: 'couple-privilege', definition: 'Kiedy para ma więcej "przywilejów" niż inni partnerzy w konfiguracji poly — mieszkają razem, wspólne finanse, decyzje taken together, inni mają się dostosować.', category: 'CNM / Poliamoria', examples: ['Couple privilege pojawia się gdy para traktuje swój związek jako ważniejszy od wszystkich innych.'] },
  { term: 'Relationship Escalator', slug: 'relationship-escalator', definition: 'Społeczny skrypt jak "powinien" wyglądać związek: randkowanie → wyłączność → zamieszkanie → zaręczyny → ślub → dzieci. W CNM wiele osób świadomie z niego schodzi.', category: 'CNM / Poliamoria', examples: ['W CNM związek może być głęboki i wartościowy bez "wspinania się" po schodach ruchomych.'] },
  { term: 'OPP (One Penis Policy)', slug: 'one-penis-policy', definition: 'Zasada w parze hetero, gdzie mężczyzna pozwala partnerce być z kobietami, ale nie z innymi mężczyznami. Powszechnie krytykowana jako seksistowska i wynikająca z insecurity.', category: 'CNM / Poliamoria', examples: ['OPP jest krytykowana za to że traktuje partnerkę jak własność i deprecjonuje jej relacje z kobietami.'] },
  { term: 'DADT (Don\'t Ask, Don\'t Tell)', slug: 'dadt', definition: 'Typ otwartego związku gdzie partnerzy mogą mieć seks z innymi, ale nie mówią sobie o tym. "Co się dzieje poza nami, zostaje poza nami."', category: 'CNM / Poliamoria', examples: ['DADT działa dla niektórych par, ale bywa krytykowane za brak transparency.'] },
  { term: 'Fluid Bonding', slug: 'fluid-bonding', definition: 'Świadoma decyzja o zaprzestaniu używania prezerwatyw z konkretnym partnerem, zazwyczaj po testach STI i ustaleniu granic z innymi partnerami.', category: 'CNM / Poliamoria', examples: ['Fluid bonding wymaga wzajemnego zaufania i regularnych testów — nie robi się tego z nową osobą.'] },
  { term: 'Poly-Saturated', slug: 'poly-saturated', definition: 'Stan w którym osoba ma tyle relacji ile może zdrowo podtrzymywać — "zapełniony" emocjonalnie. Nie ma już miejsca na nowe związki.', category: 'CNM / Poliamoria', examples: ['Jestem teraz poly-saturated — trzy relacje to moje maksimum.'] },
  { term: 'Mononormatywność', slug: 'mononormatywnosc', definition: 'Założenie społeczne że monogamia jest "default", jedynym właściwym modelem związku. Wszystko inne = dziwne lub niestabilne.', category: 'CNM / Poliamoria', examples: ['"Kiedy się w końcu ustatkujesz?", "Takie związki się nie udają" — przykłady mononormatywnych komentarzy.'] },
  { term: 'Monogamish', slug: 'monogamish', definition: 'Związek zasadniczo monogamiczny, ale z ustalonymi wyjątkami. Para jest "głównie mono" ale z elastycznością i otwartością na wyjątki.', category: 'CNM / Poliamoria', examples: ['Jesteśmy monogamish — czasem mamy przygody, ale zawsze razem o tym decydujemy.'] },
  { term: 'De-escalate', slug: 'de-escalate', definition: 'Zmniejszanie intensywności związku. Np. przestajecie mieszkać razem, ale dalej jesteście parą. Przeciwieństwo "relationship escalator".', category: 'CNM / Poliamoria', examples: ['Zdecydowaliśmy się de-escalować — teraz mieszkamy osobno, ale relacja jest zdrowsza.'] },
  { term: 'Check-in', slug: 'check-in', definition: 'Regularne rozmowy z partnerem o tym jak się czujecie w związku, czy są jakieś problemy, co można poprawić. W CNM extra ważne, bo więcej "moving parts".', category: 'CNM / Poliamoria', examples: ['Co tydzień mamy check-in — 30 minut tylko na rozmowę o nas.'] },
  { term: 'FWB (Friends with Benefits)', slug: 'fwb', definition: 'Przyjaciele którzy uprawiają ze sobą seks. Brak romantycznego zaangażowania, no strings attached. Może być częścią sieci CNM.', category: 'CNM / Poliamoria', examples: ['Mamy FWB — lubimy się, spędzamy czas, ale żadne z nas nie chce "czegoś więcej".'] },
  { term: 'Comet', slug: 'comet', definition: 'Partner z którym spotykasz się rzadko (np. przy okazji podróży), ale relacja jest silna i wartościowa mimo dystansu.', category: 'CNM / Poliamoria', examples: ['On jest moim comet — widzimy się 3-4 razy w roku, ale to ważna relacja.'] },
  { term: 'Ethical Slut', slug: 'ethical-slut', definition: 'Termin z kultowej książki (The Ethical Slut). Osoba świadomie i etycznie aktywna seksualnie z wieloma partnerami. Odebrana przez środowisko CNM jako pozytywna i emancypacyjna.', category: 'CNM / Poliamoria', examples: ['"The Ethical Slut" to lektura obowiązkowa dla każdego zaczynającego w CNM.'] },

  // === SWINGING / LIFESTYLE ===
  { term: 'Swinging', slug: 'swinging', definition: 'Styl życia w którym pary (głównie hetero) konsensualnie wymieniają się partnerami seksualnymi lub uczestniczą w grupowych aktywnościach seksualnych. Inaczej niż w poly — focus na seks, nie na emocje.', category: 'Swinging / Lifestyle', examples: ['Para od lat praktykuje swinging w zamkniętym kręgu zaufanych przyjaciół.'] },
  { term: 'The Lifestyle', slug: 'the-lifestyle', definition: 'Jak swinging community nazywa siebie. "Jesteśmy w lifestyle." Termin parasolowy dla środowiska swingerskiego.', category: 'Swinging / Lifestyle', examples: ['"Jesteśmy w lifestyle od 3 lat" — czyli od 3 lat aktywnie uczestniczą w swinger scene.'] },
  { term: 'Soft Swap', slug: 'soft-swap', definition: 'Wymiana partnerów z ograniczonym kontaktem seksualnym — oral, touching, petting ok; penetracja — nie. Dla par które dopiero zaczynają lub mają takie granice.', category: 'Swinging / Lifestyle', examples: ['Zaczęliśmy od soft swap żeby poczuć jak to jest, zanim zdecydujemy się na więcej.'] },
  { term: 'Full Swap', slug: 'full-swap', definition: 'Pełna wymiana partnerów włącznie z penetracją. Wszystkie aktywności seksualne są ok.', category: 'Swinging / Lifestyle', examples: ['Para zdecydowała się na full swap po roku soft swappingu.'] },
  { term: 'Same Room', slug: 'same-room', definition: 'Swap gdzie wszyscy pozostają w tym samym pokoju. Widzicie się nawzajem. Niektóre pary czują się bezpieczniej, gdy mogą mieć oko na partnera.', category: 'Swinging / Lifestyle', examples: ['Same room pozwala pozostać w kontakcie wzrokowym z partnerem podczas zabawy.'] },
  { term: 'Separate Room', slug: 'separate-room', definition: 'Pary idą do osobnych pokoi. Nie widzisz co Twój partner robi. Wymaga więcej zaufania i wyższego poziomu komfortu.', category: 'Swinging / Lifestyle', examples: ['Po roku w lifestyle zdecydowali się na separate room — wzajemne zaufanie jest na to gotowe.'] },
  { term: 'Hotwife', slug: 'hotwife', definition: 'Żona uprawia seks z innymi mężczyznami (i/lub kobietami) za wiedzą i zgodą męża. Focus na przyjemności kobiety. Mąż zazwyczaj sam nie śpi z innymi.', category: 'Swinging / Lifestyle', examples: ['W hotwifing chodzi o wolność i spełnienie kobiety — mąż z dumą i podnieceniem wspiera jej przygody.'] },
  { term: 'Cuckold / Cuckolding', slug: 'cuckolding', definition: 'Mąż (cuckold) podniecony jest patrzeniem jak żona uprawia seks z innym mężczyzną (bull). Często zawiera element upokorzenia — bull jest "lepszy", mąż może być poniżany. Może być bi lub straight.', category: 'Swinging / Lifestyle', examples: ['Cuckolding to świadoma gra z dominacją i uległością — kluczowa jest zgoda i negocjacja.'] },
  { term: 'Bull', slug: 'bull', definition: 'Mężczyzna który uprawia seks z hotwife lub żoną cuckold. Stereotypowo: pewny siebie, dominant. Rzeczywistość bywa różna.', category: 'Swinging / Lifestyle', examples: ['Bull w hotwifing jest partnerem żony — zazwyczaj nie ma relacji z mężem.'] },
  { term: 'Stag / Vixen', slug: 'stag-vixen', definition: 'Podobne do hotwife/cuckolding, ale BEZ elementu upokorzenia. Stag (mąż) z dumą i podnieceniem ogląda vixen (żonę) z innymi. Pozytywne nastawienie, nie upokorzenie.', category: 'Swinging / Lifestyle', examples: ['Stag/vixen to dla par które chcą seksualnej wolności bez humiliation dynamics.'] },
  { term: 'MFM / MMF', slug: 'mfm-mmf', definition: 'Threesome z kobietą i dwoma mężczyznami. MFM = mężczyźni nie mają kontaktu ze sobą (focus on woman). MMF = mężczyźni też się bawią ze sobą (bi).', category: 'Swinging / Lifestyle', examples: ['Para szuka partnera do MFM — obu mężczyzn interesuje wyłącznie kobieta.'] },
  { term: 'FMF / FFM', slug: 'fmf-ffm', definition: 'Threesome z mężczyzną i dwiema kobietami. FMF = kobiety nie mają kontaktu ze sobą. FFM = kobiety też się bawią ze sobą (bi/bi-curious).', category: 'Swinging / Lifestyle', examples: ['Para szuka kobiety do FFM — obydwie kobiety są bi.'] },
  { term: 'Gang Bang', slug: 'gang-bang', definition: 'Jedna osoba (zazwyczaj kobieta) uprawia seks z wieloma partnerami (zazwyczaj mężczyznami) jednocześnie lub po kolei.', category: 'Swinging / Lifestyle', examples: ['Gang bang to jeden z typowych tematycznych eventów w klubach swingerskich.'] },
  { term: 'Reverse Gang Bang', slug: 'reverse-gang-bang', definition: 'Jeden mężczyzna uprawia seks z wieloma kobietami jednocześnie lub po kolei. Rzadsze niż klasyczny gang bang.', category: 'Swinging / Lifestyle', examples: ['Reverse gang bang pojawia się rzadziej, ale jest organizowany na specjalnych imprezach.'] },
  { term: 'Train', slug: 'train', definition: 'Osoba uprawia seks z wieloma partnerami, ale kolejno (nie jednocześnie). W kolejce.', category: 'Swinging / Lifestyle', examples: ['Train różni się od orgy — tutaj chodzi o kolejność, nie o jednoczesność.'] },
  { term: 'Orgy / Group Play', slug: 'orgy', definition: 'Seks z wieloma osobami jednocześnie (5+). Może być zorganizowany (w klubie) lub spontaniczny.', category: 'Swinging / Lifestyle', examples: ['Orgy w lifestyle clubie odbywa się w specjalnie wyposażonych salach.'] },
  { term: 'Voyeur', slug: 'voyeur', definition: 'Osoba która lubi patrzeć jak inni uprawiają seks. Podnieta ze spektatorstwa.', category: 'Swinging / Lifestyle', examples: ['Wiele lifestyle clubs ma specjalne voyeur rooms — możesz patrzeć, ale nie dołączać.'] },
  { term: 'Exhibitionista', slug: 'exhibicjonista', definition: 'Osoba która lubi być oglądana podczas seksu. Podnieta z bycia obserwowanym.', category: 'Swinging / Lifestyle', examples: ['W lifestyle clubs exhibitioniści mogą bawić się w open playrooms.'] },
  { term: 'Hall Pass', slug: 'hall-pass', definition: 'Pozwolenie od partnera żeby uprawiać seks z kimś innym solo, bez obecności partnera. "Przepustka" na randkę poza główną parą.', category: 'Swinging / Lifestyle', examples: ['"Mam hall pass na ten weekend" — mogę się spotkać z kimś solo.'] },
  { term: 'Playroom', slug: 'playroom', definition: 'Pokój w lifestyle club wyposażony do seksu. Może być public (otwarty na patrzenie), private (zamknięty) lub semi-private.', category: 'Swinging / Lifestyle', examples: ['Public playroom pozwala innym patrzeć, private daje pełną prywatność.'] },
  { term: 'Dress Code', slug: 'dress-code', definition: 'Zasady ubioru w lifestyle club. Zazwyczaj: mężczyźni — spodnie i koszula, bez trampek; kobiety — sukienka, bielizna, obcasy. Po północy często "only towels" lub lingerie.', category: 'Swinging / Lifestyle', examples: ['Dress code w lifestyle klubach jest zazwyczaj seksowny ale elegancki — nie przychodzi się w dżinsach i t-shircie.'] },
  { term: 'Newbies', slug: 'newbies', definition: 'Para lub osoba która dopiero zaczyna w lifestyle. Nowi, często nervous, z dużą ilością pytań, eksplorujący swoje granice.', category: 'Swinging / Lifestyle', examples: ['Jako newbies zaczęliśmy od Meet & Greet zanim zdecydowaliśmy się na wizytę w klubie.'] },
  { term: 'Discretion', slug: 'discretion', definition: 'Zachowanie lifestyle w tajemnicy przed "vanilla" życiem — pracą, rodziną, znajomymi. Zasady: brak zdjęć bez zgody, nie ujawnianie danych osobowych, "co się dzieje w klubie, zostaje w klubie".', category: 'Swinging / Lifestyle', examples: ['Discretion to podstawa — wiele osób nie chce być "outed" w swoim środowisku zawodowym.'] },
  { term: 'Verify / Weryfikacja', slug: 'weryfikacja', definition: 'Potwierdzenie że profil na portalu lifestyle jest prawdziwy. Zazwyczaj przez video call lub spotkanie. Ważne bo dużo fake profiles online.', category: 'Swinging / Lifestyle', examples: ['Zanim się spotkamy, prosimy o weryfikację video — to standard w naszym środowisku.'] },
  { term: 'Chemistry', slug: 'chemistry', definition: 'Wzajemna atrakcja między parami. Musi być żeby zagrać. "No chemistry" to grzeczna odmowa — nic złego, po prostu nie ma flow.', category: 'Swinging / Lifestyle', examples: ['"Nie ma chemii" — polite way to decline. Doesn\'t mean anything is wrong.'] },
  { term: 'Reclaim Sex', slug: 'reclaim-sex', definition: 'Seks z Twoim partnerem PO zabawie z innymi. Reconnecting, potwierdzenie waszego związku. Bardzo powszechne — pary wracają do siebie po sesji.', category: 'Swinging / Lifestyle', examples: ['Po każdej imprezie lifestyle zawsze mamy swój czas — reclaim sex jest ważną częścią naszego rytuału.'] },
  { term: 'GGG (Good, Giving, Game)', slug: 'ggg', definition: 'Filozofia od Dana Savage. Bądź: Good (dobry w łóżku), Giving (dbaj o potrzeby partnera), Game (otwarty na nowe rzeczy w granicach rozsądku).', category: 'Swinging / Lifestyle', examples: ['GGG to postawa którą ceni lifestyle community — wzajemność i otwartość.'] },
  { term: 'Meet & Greet', slug: 'meet-and-greet', definition: 'Casualowe spotkanie towarzyskie dla ludzi z lifestyle community w publicznym miejscu (kawiarnia, restauracja). Bez seksu, tylko poznawanie. Świetne dla newbies.', category: 'Swinging / Lifestyle', examples: ['Zaczęliśmy od Meet & Greet — pozwoliło nam poznać kilka par przed pójściem do klubu.'] },
  { term: 'Hotel Takeover', slug: 'hotel-takeover', definition: 'Impreza gdzie lifestyle group rezerwuje większość pokoi w hotelu na weekend. Prywatne parties, pool parties, etc. Całość jest dla swingers.', category: 'Swinging / Lifestyle', examples: ['Hotel takeover to intensywniejsze doświadczenie niż klub — cały weekend w jednym miejscu.'] },
  { term: 'House Party', slug: 'house-party', definition: 'Lifestyle party zorganizowane w czyimś domu. Zazwyczaj tylko na zaproszenie, sprawdzone osoby. Bardziej intymne niż klub.', category: 'Swinging / Lifestyle', examples: ['House party są kameralne i przyjazne — znasz prawie każdego.'] },
  { term: 'Lifestyle Friendly', slug: 'lifestyle-friendly', definition: 'Hotel, resort lub lokal który jest ok z lifestyle gośćmi — nie wyrzuci Cię za PDAs lub wiele osób w pokoju.', category: 'Swinging / Lifestyle', examples: ['Szukamy lifestyle friendly hotelu na weekend — potrzebujemy swobody.'] },
  { term: 'On-premise', slug: 'on-premise', definition: 'Wydarzenie lub klub gdzie aktywność seksualna ma miejsce na miejscu. Jest specjalna strefa zabaw.', category: 'Swinging / Lifestyle', examples: ['To on-premise event — jest specjalna strefa play na piętrze.'] },
  { term: 'Off-premise', slug: 'off-premise', definition: 'Wydarzenie towarzyskie BEZ aktywności seksualnej na miejscu. Flirty ok, seks — umów się prywatnie.', category: 'Swinging / Lifestyle', examples: ['To off-premise party — Meet & Greet, poznajemy się, a potem każdy układa się osobno.'] },
  { term: 'No Means No', slug: 'no-means-no', definition: 'Zero tolerance policy. Jeśli ktoś mówi "nie" — natychmiastowe stop. Brak negocjacji. Naruszenie = stałe wyrzucenie z klubu.', category: 'Swinging / Lifestyle', examples: ['No means no to absolutna zasada w lifestyle community — szanujemy granice zawsze.'] },
  { term: 'Lifestyle Club / Swinger Club', slug: 'lifestyle-club', definition: 'Klub gdzie pary (i czasem single) spotykają się żeby uprawiać seks. Zazwyczaj: bar/lounge, dance floor, playrooms, jacuzzi/sauna. W Polsce: Lava, Elysium, Jacuzzi Club, Heaven, Bordeaux.', category: 'Swinging / Lifestyle', examples: ['Lifestyle club to bezpieczna przestrzeń gdzie wszystko odbywa się za zgodą i w dyskrecji.'] },
  { term: 'Single Female (SF)', slug: 'single-female', definition: 'Kobieta single w lifestyle scene. Bardzo mile widziane, często wchodzą za free lub po niższej cenie. Popyt jest wyższy niż podaż.', category: 'Swinging / Lifestyle', examples: ['Single female zawsze są mile widziane w lifestyle clubs.'] },
  { term: 'Single Male (SM)', slug: 'single-male', definition: 'Mężczyzna single w lifestyle scene. Trudniej dostać się na eventy — wyższe ceny, limitowane miejsca. Bo jest znacznie więcej chętnych mężczyzn niż miejsc.', category: 'Swinging / Lifestyle', examples: ['Dla single male lifestyle scene jest trudniejsza — wiele klubów ma limit lub wyższe ceny.'] },

  // === BDSM / KINK ===
  { term: 'BDSM', slug: 'bdsm', definition: 'Umbrella term obejmujący: B&D (Bondage & Discipline — wiązanie i dyscyplina), D/s (Dominance & Submission — dominacja i uległość), S&M (Sadism & Masochism — sadyzm i masochizm).', category: 'BDSM / Kink', examples: ['BDSM wymaga dokładnego omówienia granic przed każdą sesją.'] },
  { term: 'Kink', slug: 'kink', definition: 'Wszystko co wykracza poza "vanilla sex". Szersze niż BDSM — obejmuje fetisze, role play i inne niestandardowe praktyki. Przykłady: impact play, rope bondage, age play, pet play.', category: 'BDSM / Kink', examples: ['Każdy ma swoje kinki — ważne żeby omówić je z partnerem.'] },
  { term: 'Safeword', slug: 'safeword', definition: 'Umówione słowo lub sygnał służące do natychmiastowego przerwania aktywności BDSM. Używając safeword — wszystko się zatrzymuje. Brak dyskusji, brak negocjacji.', category: 'BDSM / Kink', examples: ['Naszym safeword jest "ananasy" — jak tylko je powie, wszystko zatrzymujemy.'] },
  { term: 'Red / Yellow / Green', slug: 'red-yellow-green', definition: 'Popularny system safeword: Red = stop natychmiast, Yellow = zwolnij / muszę porozmawiać, Green = wszystko ok, dalej.', category: 'BDSM / Kink', examples: ['Używamy systemu Red/Yellow/Green — Yellow nie znaczy stop, tylko "daj mi chwilę".'] },
  { term: 'SSC (Safe, Sane, Consensual)', slug: 'ssc', definition: 'Filozofia BDSM: wszystko powinno być Bezpieczne (minimalizujesz ryzyko), Świadome (robisz to z czystym umysłem) i Za Zgodą (wszyscy się zgadzają).', category: 'BDSM / Kink', examples: ['SSC to klasyczna filozofia — wiele środowisk uzupełnia ją nowszymi podejściami jak RACK.'] },
  { term: 'RACK (Risk-Aware Consensual Kink)', slug: 'rack', definition: 'Nowsza filozofia BDSM. Żadna praktyka nie jest 100% bezpieczna, ale możesz być świadomy ryzyk i zgadzać się na nie. Bardziej realistyczne niż SSC.', category: 'BDSM / Kink', examples: ['RACK pozwala na bardziej zaawansowane praktyki przy pełnej świadomości ryzyka.'] },
  { term: 'Dom / Domina', slug: 'dom-domina', definition: 'Osoba dominująca w D/s relationship. Bierze kontrolę, daje komendy. Dom = mężczyzna dominant, Domme/Domina = kobieta dominant. Warianty: Daddy/Mommy Dom (nurturing), Master/Mistress (strict).', category: 'BDSM / Kink', examples: ['Jako Domme, ona ustala zasady i granice ich sesji.'] },
  { term: 'Sub / Submissive', slug: 'sub', definition: 'Osoba uległa w D/s relationship. Oddaje kontrolę, słucha komend. Bycie submissive to aktywny wybór — wymaga siły i zaufania, nie jest oznaką słabości.', category: 'BDSM / Kink', examples: ['On chętnie przyjmuje rolę suba w ich dynamice — to jego świadomy wybór.'] },
  { term: 'Switch', slug: 'switch', definition: 'Osoba która może być zarówno dominant jak i submissive — w zależności od partnera, nastroju i sytuacji. Z jednym jest Dom, z innym Sub.', category: 'BDSM / Kink', examples: ['Jako switch lubi zarówno dowodzić jak i być prowadzona.'] },
  { term: 'Top / Bottom', slug: 'top-bottom', definition: 'Top = osoba która "robi" coś podczas scene (wiąże, uderza, penetruje). Bottom = osoba której "robi się" (jest wiązana, przyjmuje uderzenia). Różne od Dom/Sub — Top/Bottom to fizyczna rola, nie power exchange.', category: 'BDSM / Kink', examples: ['Można być "service top" — robisz wszystko ale Sub ma kontrolę nad sceną.'] },
  { term: 'Power Exchange', slug: 'power-exchange', definition: 'Przekazanie władzy i kontroli z jednej osoby na drugą. Centrum BDSM. Może trwać tylko podczas scene, w życiu codziennym (24/7) lub Total Power Exchange (TPE).', category: 'BDSM / Kink', examples: ['Power exchange to nie przemoc — to świadome, negocjowane oddanie i przyjęcie władzy.'] },
  { term: 'Scene', slug: 'scene', definition: 'Konkretna sesja BDSM. Ma negocjowany początek, przebieg i koniec. "Mieliśmy wczoraj scene przez 2 godziny — rope bondage i impact play."', category: 'BDSM / Kink', examples: ['Scene zawsze zaczyna się od negocjacji — co będziemy robić, co jest off-limits, jakie safeword.'] },
  { term: 'Aftercare', slug: 'aftercare', definition: 'Opieka i wsparcie po intensywnych aktywnościach BDSM — przytulanie, rozmowa, woda, koc. BDSM może być intensywny fizycznie i emocjonalnie, aftercare pomaga wrócić do "normalności".', category: 'BDSM / Kink', examples: ['Po każdej sesji poświęcamy godzinę na aftercare — przytulanie i rozmowę o tym co przeżyliśmy.'] },
  { term: 'Sub Drop / Dom Drop', slug: 'sub-drop', definition: 'Emocjonalny kryzys po intensywnej scenie. Wynika ze spadku endorfin i adrenaliny. Objawy: smutek, anxiety, poczucie odłączenia, płaczliwość. Lekarstwo: aftercare, bliskość, odpoczynek.', category: 'BDSM / Kink', examples: ['Dzień po intensywnej scene poczułam sub drop — byłam smutna bez powodu. Mój Dom był ze mną.'] },
  { term: 'Subspace', slug: 'subspace', definition: 'Stan głębokiego relaksu i euforii podczas scene. Sub czuje się "high", może być non-verbal, bardzo uległy. Wynika z zalewu endorfin i zaufania. Ważne: Sub w subspace może nie być w stanie używać safeword.', category: 'BDSM / Kink', examples: ['Gdy wchodzi w subspace, Dom musi być extra uważny — ona może nie być w stanie powiedzieć stop.'] },
  { term: 'Negocjacja', slug: 'negocjacja-bdsm', definition: 'Rozmowa przed scene o tym co będziecie robić, jakie są granice, co jest ok a co nie. Must discuss: hard limits, soft limits, safeword, aftercare needs, triggery.', category: 'BDSM / Kink', examples: ['Negocjacja przed scene to obowiązek — bez niej nie zaczynamy.'] },
  { term: 'Hard Limit', slug: 'hard-limit', definition: 'Absolutna granica której przekraczać nie wolno. Non-negotiable. "Anal sex is my hard limit", "No blood play". Nawet Dom musi to uszanować.', category: 'BDSM / Kink', examples: ['Hard limit to nieprzekraczalna linia — nawet w trakcie scene, nawet jeśli sub jest w subspace.'] },
  { term: 'Soft Limit', slug: 'soft-limit', definition: 'Rzecz której zazwyczaj nie robisz, ale może w odpowiednich warunkach, z odpowiednią osobą, po większej ilości rozmów. Granica "może, zależy od kontekstu".', category: 'BDSM / Kink', examples: ['Spanking to mój soft limit — nie z każdym, ale z Tobą, po negocjacji, ok.'] },
  { term: 'Bondage', slug: 'bondage', definition: 'Wiązanie partnera — ograniczanie ruchu. Typy: rope bondage (shibari, kinbaku), kajdanki (cuffs), tape bondage, suspension (wieszanie w powietrzu).', category: 'BDSM / Kink', examples: ['Bondage to nie tylko wiązanie — to zaufanie i estetyka.'] },
  { term: 'Shibari / Kinbaku', slug: 'shibari', definition: 'Japońska sztuka rope bondage. Shibari = dekoracyjna, artystyczna. Kinbaku = erotyczna, celowo krępująca. W Polsce rosnąca scena, warsztaty w większych miastach.', category: 'BDSM / Kink', examples: ['Shibari to sztuka — sesje mogą być artystyczne, bez kontekstu seksualnego.'] },
  { term: 'Impact Play', slug: 'impact-play', definition: 'Uderzanie partnera dla przyjemności/bólu. Spanking, flogging, caning. Narzędzia: ręka, łopatka (paddle), bat (flogger), trzcina (cane). Bezpieczne strefy: pośladki, uda, plecy (NIE głowa, szyja, nerki).', category: 'BDSM / Kink', examples: ['Impact play zaczynamy od lekkiego spanking ręką — potem ewoluujemy w kierunku flogger.'] },
  { term: 'Brat', slug: 'brat', definition: 'Sub który jest playfully defiant — celowo nie słucha żeby dostać "karę" (którą lubi). "Make me", eye rolling, teasing. Brat Tamer to Dom który wie jak sobie z nimi poradzić.', category: 'BDSM / Kink', examples: ['"Nie możesz mi kazać" — klasyczne zachowanie brata. Dom wie, że to zaproszenie.'] },
  { term: 'Collar', slug: 'collar', definition: 'Obroża/naszyjnik noszona przez Sub jako symbol relacji z Domem. Day collar — dyskretna, na co dzień; Play collar — do scene; Permanent collar — symbol długoterminowego zaangażowania (jak obrączka).', category: 'BDSM / Kink', examples: ['Otrzymanie permanent collar to poważny krok w D/s relationship — traktowany jak rytuał zaręczyn.'] },
  { term: 'Dungeon', slug: 'dungeon', definition: 'Przestrzeń wyposażona do BDSM — krzyż św. Andrzeja, ławka do spanking, klatka, punkty zawieszenia. Może być w klubie, prywatna, albo w domu.', category: 'BDSM / Kink', examples: ['W piwnicy mają prawdziwy dungeon z pełnym wyposażeniem.'] },
  { term: 'Munches', slug: 'munches', definition: 'Spotkania społeczne kink community w publicznym miejscu (kawiarnia, restauracja). Vanilla ubrania, zero play, tylko rozmowy i networking. Świetne dla nowych.', category: 'BDSM / Kink', examples: ['Zaczęłam od munchów — poznałam środowisko zanim zdecydowałam się na play party.'] },
  { term: 'Play Party', slug: 'play-party', definition: 'Prywatne wydarzenie gdzie ludzie robią sceny BDSM. Zazwyczaj w dungeonie lub odpowiednio wyposażonej przestrzeni. Zasady: zgoda obowiązkowa, pytaj przed dotknięciem, szanuj safeword.', category: 'BDSM / Kink', examples: ['Play party różni się od lifestyle club — focus jest na BDSM, nie na seks.'] },
  { term: 'Edge Play', slug: 'edge-play', definition: 'Bardzo ryzykowne praktyki — szara strefa między bezpiecznym a niebezpiecznym. Przykłady: breath play (duszenie), knife play, fire play, blood play. Tylko z dużym doświadczeniem i pełnym zaufaniem.', category: 'BDSM / Kink', examples: ['Edge play to nie dla początkujących — wymaga lat doświadczenia i ekstremalnego zaufania.'] },
  { term: 'Primal Play', slug: 'primal-play', definition: 'Surowy, animalistyczny seks i zabawa — polowanie, szarpanie się, gryzienie, drapanie. Role: Predator (poluje) i Prey (ucieka/chowa się).', category: 'BDSM / Kink', examples: ['Primal play to powrót do instynktów — mniej zasad, więcej intuicji i ciała.'] },
  { term: 'CNC (Consensual Non-Consent)', slug: 'cnc', definition: 'Odgrywanie scenariusza non-consent (rape fantasy) z uprzednią negocjacją i pełną zgodą. Fantasy między zgadzającymi się dorosłymi z safeword. Bardzo kontrowersyjne nawet w kink community.', category: 'BDSM / Kink', examples: ['CNC wymaga najdokładniejszej negocjacji ze wszystkich praktyk — co do szczegółu.'] },
  { term: 'Fetysz', slug: 'fetysz', definition: 'Seksualna atrakcja do konkretnego przedmiotu, części ciała lub sytuacji. Przykłady: foot fetish (stopy), latex/leather, pantyhose, smoking. Różni się od kink tym, że jest niezbędny do satysfakcji.', category: 'BDSM / Kink', examples: ['Każdy ma swoje fetysze — ważne żeby je omówić z partnerem.'] },
  { term: 'Pet Play', slug: 'pet-play', definition: 'Role play jako zwierzę. Sub zachowuje się jak pet, Dom jest owner. Puppy play (pies), kitten play (kot), pony play (koń). Może być seksualne lub nie.', category: 'BDSM / Kink', examples: ['Pet play dla wielu jest relaksem i ucieczką od dorosłych obowiązków — nie zawsze chodzi o seks.'] },
  { term: 'Chastity', slug: 'chastity', definition: 'Sub nosi urządzenie czystości (klatka na penisie lub pas cnoty) i nie może mieć orgazmu ani dotykać się bez zgody Doma. Może trwać godziny, dni, tygodnie.', category: 'BDSM / Kink', examples: ['Chastity to długoterminowy power exchange — Dom kontroluje jedną z najbardziej intymnych sfer życia.'] },
  { term: 'Edging', slug: 'edging', definition: 'Doprowadzanie kogoś blisko orgazmu i zatrzymanie. Powtarzanie. Bardzo frustrujące i jednocześnie bardzo przyjemne. Forma orgasm control/denial.', category: 'BDSM / Kink', examples: ['Edging przez godzinę, a potem permission — intensywność orgazmu jest nieporównywalna.'] },
  { term: 'Consent', slug: 'consent', definition: 'Świadoma, entuzjastyczna zgoda wszystkich stron. Musi być: ongoing (sprawdzasz czy dalej ok), odwołalna (zawsze można powiedzieć stop), informed (wiesz na co się zgadzasz), entuzjastyczna ("ok whatever" to za mało).', category: 'BDSM / Kink', examples: ['"Może" to nie jest zgoda. "Tak, chcę tego" — to jest zgoda.'] },

  // === OGÓLNE / LIFESTYLE ===
  { term: 'Vanilla', slug: 'vanilla', definition: '"Zwykły" seks lub osoba nieinteresująca się CNM/BDSM. Nie jest pejoratywne — to po prostu descriptor. "Vanilla club" = zwykły nightclub bez lifestyle.', category: 'Ogólne', examples: ['Nie ma nic złego w vanilla — każdy ma prawo do własnych preferencji.'] },
  { term: 'Play Partner', slug: 'play-partner', definition: 'Osoba z którą masz seks lub aktywności kink, ale bez pełnej relacji romantycznej. Regularni play partnerzy znają swoje granice, są przetestowani, czują się komfortowo.', category: 'Ogólne', examples: ['Mamy kilku play partnerów z którymi spotykamy się na eventach — bez romantycznego zaangażowania.'] },
  { term: 'Coming Out (CNM)', slug: 'coming-out-cnm', definition: 'Mówienie innym że jesteś w CNM/poly relationship. Podobne użycie jak w LGBT+ kontekście. Wiele osób tego nie robi ze względu na pracę, rodzinę lub społeczną stygmę. Twój wybór.', category: 'Ogólne', examples: ['Coming out przed rodziną był trudny, ale uwolniłam się od kłamstw.'] },
  { term: 'Jealousy vs Envy', slug: 'zazdrość-a-zawiść', definition: 'Zazdrość (jealousy) = strach że stracisz coś co masz. Zawiść (envy) = chcesz coś co ktoś inny ma. W CNM zazdrość jest normalna — nie znika magicznie, trzeba się nauczyć z nią pracować.', category: 'Ogólne', examples: ['Zazdrość to sygnał do zbadania własnych potrzeb — nie rozkaz do działania.'] },
  { term: 'Boundaries', slug: 'boundaries', definition: 'Granice — czego TY potrzebujesz żeby czuć się bezpiecznie. "Potrzebuję testów STI co 3 miesiące." Różne od zasad (rules) — boundaries dotyczą Ciebie, nie kontrolują partnera.', category: 'Ogólne', examples: ['Moje boundaries: zawsze zabezpieczenie z nowymi osobami, zawsze wiem gdzie jesteś.'] },
  { term: 'OSO (Other Significant Other)', slug: 'oso', definition: 'Określenie na partnera/partnerkę Twojego partnera/partnerki. Używane w poly community jako neutralne określenie.', category: 'Ogólne', examples: ['Spotkałam OSO mojego chłopaka i od razu przypadłyśmy sobie do gustu.'] },
]

export function getWordOfTheDay() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000)
  return DICTIONARY_TERMS[dayOfYear % DICTIONARY_TERMS.length]
}

export function getTerm(slug) {
  return DICTIONARY_TERMS.find(t => t.slug === slug)
}

export function getTermsByCategory() {
  const cats = {}
  for (const t of DICTIONARY_TERMS) {
    (cats[t.category] ||= []).push(t)
  }
  return cats
}
