export function slugifyTerm(term) {
  return term.toLowerCase()
    .replace(/ą/g,'a').replace(/ć/g,'c').replace(/ę/g,'e')
    .replace(/ł/g,'l').replace(/ń/g,'n').replace(/ó/g,'o')
    .replace(/ś/g,'s').replace(/ź/g,'z').replace(/ż/g,'z')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export const DICTIONARY_TERMS = [
  // === CNM / POLIAMORIA ===
  { term: 'CNM (Consensual Non-Monogamy)', slug: 'cnm', definition: 'CNM to parasol, pod którym mieści się wszystko co nie jest klasyczną monogamią — ale dzieje się za wiedzą i zgodą wszystkich zaangażowanych. Innymi słowy: nie chodzi o zdradę, chodzi o wybranie innego modelu. Obejmuje polyamorię, swinging, otwarte związki, DADT i dziesiątki innych konfiguracji. Klucz to słowo "consensual" — wszyscy wiedzą, wszyscy się zgadzają, nikt nie jest zaskoczony. CNM praktykuje szacunkowo kilka procent dorosłych, choć wielu robi to po cichu, bez etykiety. Nie ma jednego "właściwego" sposobu na CNM — to jak pizza, każdy układa swoje składniki. Wbrew obawom, badania pokazują że ludzie w CNM mają podobny poziom satysfakcji ze związku co monogamiści. Podstawowe narzędzie: komunikacja. Dużo komunikacji. Prawdopodobnie więcej niż myślisz.', category: 'CNM / Poliamoria', examples: ['CNM to szerokie pojęcie — klucz to zgoda i komunikacja, nie konkretna forma związku.'] },
  { term: 'ENM (Ethical Non-Monogamy)', slug: 'enm', definition: 'ENM to synonim CNM — używane zamiennie, zależnie od tego kogo pytasz. Słowo "ethical" (etyczna) ma podkreślać że to nie jest tylko "rób co chcesz" — tu chodzi o uczciwość, przejrzystość i szacunek dla wszystkich osób w układzie. Ktoś wymyślił ENM żeby odciąć się od skojarzeń z niewiernością i chaosem. Jeśli CNM brzmi technicznie, ENM brzmi bardziej jak deklaracja wartości. W praktyce: te same rzeczy, inna etykieta na opakowaniu. Część osób woli "CNM" bo brzmi neutralnie, inni wolą "ENM" bo podkreśla intencje. W rozmowie możesz używać obu — nikt Cię nie poprawi.', category: 'CNM / Poliamoria', examples: ['ENM kładzie nacisk na uczciwość — dlatego "ethical" w nazwie.'] },
  { term: 'Poliamoria', slug: 'poliamoria', definition: 'Poliamoria to zdolność i chęć kochania więcej niż jednej osoby jednocześnie — i robienie tego otwarcie, za wiedzą wszystkich. Różni się od swingingu tym, że chodzi nie tylko o seks, ale też o emocje, przywiązanie, może wspólne życie. Nazwa pochodzi z greckiego "poly" (wiele) i łacińskiego "amor" (miłość) — lingwistyczny miszmasz, który jakoś się przyjął. Wbrew popularnemu mitowi, polyamoria nie oznacza że kochasz każdego tak samo — każda relacja jest inna, tak jak są różni ludzie. Często słyszysz "ale jak możesz kochać więcej niż jedną osobę?" — to jak pytać rodzica czy mniej kocha drugie dziecko bo urodziło się pierwsze. Miłość nie jest pizzą do podziału na kawałki. Polyamoria wymaga dużo komunikacji, samoświadomości i czasu — to nie jest łatwiejsze niż monogamia, po prostu inne.', category: 'CNM / Poliamoria', examples: ['Ania jest w związku z Markiem od 5 lat i od roku spotyka się też z Kasią. Wszyscy o tym wiedzą i się wspierają.'] },
  { term: 'Otwarty związek', slug: 'otwarty-zwiazek', definition: 'W otwartym związku para ma główną relację emocjonalną i romantyczną tylko ze sobą — ale seks z innymi osobami jest ok. Emocje zostają w domu, ciało może podróżować. To jedna z najbardziej popularnych form CNM, często pierwsza próba dla par które chcą "otworzyć" związek. Kluczowe pytanie do ustalenia na początku: co dokładnie jest "otwarte"? Czy mogą być randki? Czy nocowanie u kogoś innego jest ok? Czy w twoim mieście, czy tylko w delegacji? Każda para ustala własne zasady — nie ma jednego wzorca. Częsty błąd: para otwiera związek licząc że rozwiąże to inne problemy. Nie rozwiązuje — raczej amplifikuje to co już jest. Jeśli związek jest zdrowy, może być fajną przygodą.', category: 'CNM / Poliamoria', examples: ['W otwartym związku można mieć przygody, ale romantyczne zaangażowanie zostaje w parze.'] },
  { term: 'Polyfidelity / Poliwierność', slug: 'polyfidelity', definition: 'Polyfidelity to zamknięta grupa ludzi — na przykład trójka lub czwórka — którzy są razem nawzajem i tylko ze sobą. Brzmi paradoksalnie: "wierna poliamoria"? Tak, dokładnie. Myśl o tym jak o monogamii, tylko rozszerzonej na więcej osób. Wszyscy w grupie wiedzą o wszystkich, wszyscy są ze wszystkimi, nikt nie szuka niczego "na zewnątrz" bez rozmowy z resztą. To jedna z bardziej stabilnych konfiguracji CNM — jeśli dynamika grupowa działa. Wymaga dużo wzajemnego zaufania i jasnych rozmów o tym co się dzieje gdy ktoś chce poszerzyć grupę. Popularne wśród ludzi którzy chcą bliskości i zaangażowania, ale nie są przekonani do klasycznej pary. Trójki i czwórki polyfidelity istnieją od dekad — po prostu rzadko o tym mówią głośno.', category: 'CNM / Poliamoria', examples: ['Adam, Ewa i Tomek są razem od 3 lat. To ich zamknięta trójka.'] },
  { term: 'Compersion', slug: 'compersion', definition: 'Compersion to uczucie radości i ciepła które czujesz widząc że Twój partner jest szczęśliwy z kimś innym. Często opisywane jako "przeciwieństwo zazdrości" — choć to nie do końca precyzyjne, bo można mieć jednocześnie i jedno, i drugie. Słowo nie istnieje w słowniku polskim ani angielskim — wymyśliła je społeczność poly w latach 90. i się przyjęło. Brzmi abstrakcyjnie dopóki tego nie poczujesz — wtedy nagle rozumiesz dlaczego people in poly są tak podekscytowani tym słowem. Compersion nie jest obowiązkowe ani "dowodem" że jesteś "dobry w poly" — niektórzy nigdy tego nie czują i to też jest ok. Jeśli Twój partner wraca ze szczęśliwą miną z randki i Ty czujesz się z tym dobrze albo wręcz cieszysz — właśnie to jest compersion. Bywa mylone z brakiem uczuć, ale to coś zupełnie innego: to aktywna, pozytywna emocja, nie obojętność.', category: 'CNM / Poliamoria', examples: ['Widzisz że Twoja dziewczyna świetnie się bawi na randce z kimś innym i czujesz radość zamiast zazdrości — to compersion.'] },
  { term: 'NRE (New Relationship Energy)', slug: 'nre', definition: 'NRE to ta intensywna, rozedrgana faza na początku nowej relacji — kiedy non-stop myślisz o tej osobie, wszystko wydaje się idealne, seks jest niesamowity i masz wrażenie że wreszcie rozumiesz o co chodzi w życiu. To biochemia: dopamina, oksytocyna i adrenalina robią swoje. Trwa zwykle od kilku miesięcy do półtora roku, potem opada — i to jest normalne, nie oznacza że związek umiera. W CNM NRE jest szczególnie ważne bo gdy partner wchodzi w nową relację, jego energia i czas mogą się przesunąć w tamtą stronę. Dla osób z boku może to boleć — nawet jeśli rozumiesz to racjonalnie, emocje mają swoje zdanie. Dobra praktyka: mów partnerowi gdy czujesz że NRE go "wciąga" kosztem Waszego czasu. Warto też pamiętać że osoby w NRE mają tendencję do podejmowania impulsywnych decyzji — wstrzymaj się z dużymi zobowiązaniami dopóki mgła nie opadnie.', category: 'CNM / Poliamoria', examples: ['W fazie NRE wszystko wydaje się idealne — warto zachować zdrowy rozsądek i rozmawiać z partnerem.'] },
  { term: 'Metamour', slug: 'metamour', definition: 'Metamour to partner Twojego partnera — osoba z którą nie jesteś w relacji romantycznej, ale jesteście połączeni przez kogoś wspólnego. Jeśli jesteś z Anią, a Ania jest też z Tomkiem — Tomek jest Twoim metamourem. Nie musicie być przyjaciółmi, nie musicie się lubić, choć miło gdy tak jest. Relacja z metamourem może być wszystkim: od "hej, cześć" przez SMS po prawdziwa przyjaźń i wspólne obiady. W kitchen table poly metamours się znają i lubią. W parallel poly możesz nawet nie znać ich imienia. Wiele osób odkrywa że metamourowie są całkiem fajnymi ludźmi — w końcu mają dobry gust, skoro wybrali tego samego partnera co Ty. Słowo pochodzi ze środowiska poly anglojęzycznego i nie ma dobrego polskiego odpowiednika — "partner partnera" brzmi jak łamigłówka, więc metamour zostaje.', category: 'CNM / Poliamoria', examples: ['Mój metamour i ja lubimy wspólnie gotować, choć nie jesteśmy parą.'] },
  { term: 'Polycule', slug: 'polycule', definition: 'Polycule to cała sieć osób połączonych relacjami poliamorycznymi — bezpośrednio lub pośrednio. Nazwa pochodzi od "molecule" — tak jak atomy w cząsteczce, ludzie są połączeni różnymi wiązaniami. Ty jesteś z Anią, Ania jest z Tomkiem, Tomek jest z Kasią i Piotrem — to jest jeden polycule. Konfiguracje bywają skomplikowane jak diagram chemiczny i niektórzy naprawdę rysują schematy żeby się nie pogubić. Polycule może być małe (trzy osoby) albo rozrastać się do kilkunastu gdy relacje się splatają przez lata. Nie wszyscy w polycule muszą się znać ani lubić — ale zazwyczaj jest jakaś świadomość że "należymy do tej samej sieci". W środowisku poly słyszysz czasem "mój polycule" z prawdziwą dumą — to jak powiedzieć "moja rodzina", tyle że z wyboru.', category: 'CNM / Poliamoria', examples: ['Ty jesteś z Anią, Ania jest z Tomkiem, Tomek jest z Kasią — to jest Twój polycule.'] },
  { term: 'Unicorn', slug: 'unicorn', definition: 'Unicorn to biseksualna kobieta gotowa dołączyć do istniejącej pary hetero (mężczyzna + kobieta) jako "trzecia" — i być z obojgiem jednocześnie, na ich warunkach. Nazwa pochodzi stąd że taka osoba jest rzadka jak jednorożec — i słusznie, bo oczekiwania par bywają nierealistyczne. Para często szuka kogoś kto będzie "pasował idealnie" do obu, nie będzie miał własnych potrzeb emocjonalnych, nie zagrozi ich związkowi i zniknie gdy para zdecyduje. Unicorny z kolei są pełnoprawnymi ludźmi z własnym życiem, uczuciami i oczekiwaniami — co często zaskakuje pary szukające "dodatku". Termin bywa używany przez same te kobiety z humorem i dystansem, czasem z rozmysłem jako self-identifier. Jeśli szukasz unicorna — zanim wyślesz kolejne ogłoszenie, zastanów się co możesz zaoferować tej osobie, nie tylko czego oczekujesz.', category: 'CNM / Poliamoria', examples: ['Wiele par szuka unicorna, ale warto pamiętać o podmiotowości takiej osoby.'] },
  { term: 'Unicorn Hunting', slug: 'unicorn-hunting', definition: 'Unicorn hunting to aktywne poszukiwanie przez parę biseksualnej kobiety do trójkąta — i niestety często w sposób który nie uwzględnia jej jako pełnoprawnego uczestnika. Red flags w ogłoszeniach: "must love us both equally", "no drama", "nie możecie spotykać się osobno", "nasze zasady". Para zakłada że trzecia osoba dopasuje się do ich dynamiki, nie będzie chciała niczego "za dużo" i zniknie gdy nie będzie już potrzebna. W efekcie unicorn hunting jest krytykowane w społeczności poly jako traktowanie drugiego człowieka jak zabawki, nie partnera. Nie oznacza to że trójki nie mogą działać — mogą i działają świetnie. Różnica jest prosta: jeśli trzecia osoba ma takie same prawa i głos jak reszta, to nie jest hunting. Jeśli ma się dopasować do Waszego gotowego scenariusza — to jest.', category: 'CNM / Poliamoria', examples: ['Unicorn hunting bywa problematyczne gdy para traktuje trzecią osobę jako dodatek, nie równorzędnego partnera.'] },
  { term: 'Primary / Secondary Partner', slug: 'primary-secondary-partner', definition: 'W modelu hierarchicznym poly partnerzy mają różne "poziomy" — primary to partner główny (najczęściej mieszkacie razem, macie wspólne finanse, decydujecie razem o ważnych sprawach), secondary to partner drugorzędny, który ma mniej "przywilejów". Brzmi zimno i trochę jest. Zwolennicy mówią że to uczciwe i przejrzyste — każdy wie na czym stoi. Krytycy mówią że uprzedmiotawia secondary partnerów, sprowadzając ich do roli "drugorzędnych". W praktyce wiele osób używa tych słów żeby opisać realia swojego życia, nie żeby kogoś umniejszyć. Alternatywą jest model non-hierarchiczny gdzie nie ma formalnej hierarchii — każda relacja jest ceniona za siebie. Jeśli rozważasz hierarchical poly, warto porozmawiać z potential secondary partnerem o tym czego się spodziewać — zanim ktoś się zakoccha i odkryje że ma być "na drugim miejscu".', category: 'CNM / Poliamoria', examples: ['W hierarchical poly partner primary często ma prawo weta przy nowych relacjach.'] },
  { term: 'Nesting Partner', slug: 'nesting-partner', definition: 'Nesting partner to osoba z którą dzielisz przestrzeń życiową — mieszkacie razem, macie wspólną łazienkę, kłócicie się o zmywarkę. "Nesting" od angielskiego "nest" — gniazdo. To ważne rozróżnienie w poly, bo zamieszkanie razem nie musi oznaczać że ta relacja jest "ważniejsza" od innych. Można mieć nesting partnera i jednocześnie równie głęboką relację z kimś kto mieszka po drugiej stronie miasta. Wspólne mieszkanie to praktyczna konfiguracja, nie hierarchia emocjonalna — przynajmniej w teorii. W praktyce bycie nesting partnerem często wiąże się z większą ilością czasu razem i naturalnym "uprzywilejowaniem" logistycznym. Warto być tego świadomym i rozmawiać z innymi partnerami o tym jak to wpływa na ich poczucie miejsca w Twoim życiu.', category: 'CNM / Poliamoria', examples: ['Mieszkam z Tomkiem (nesting partner), ale mój związek z Asią jest równie ważny emocjonalnie.'] },
  { term: 'Anchor Partner', slug: 'anchor-partner', definition: 'Anchor partner to osoba która jest Twoim głównym emocjonalnym punktem odniesienia — Twoja kotwica. Niekoniecznie mieszkacie razem, niekoniecznie jesteście "primary" w formalnym sensie, ale to do tej osoby wracasz gdy coś jest trudne, z nią świętuje sukcesy i przy niej czujesz się najbardziej sobą. Termin pochodzi ze środowisk non-hierarchical poly jako alternatywa dla "primary" — mniej korporacyjna, bardziej emocjonalna. Anchor partner to nie tytuł który się nadaje, to rola którą ktoś naturalnie zajmuje w Twoim życiu. Możesz mieć więcej niż jedną taką osobę, albo żadnej — i to też jest ok w ramach solo poly. Dobrze jest powiedzieć komuś wprost że jest Twoją kotwicą — ludzie lubią wiedzieć że są ważni.', category: 'CNM / Poliamoria', examples: ['Ona jest moim anchor partner — zawsze do niej wracam po trudnych chwilach.'] },
  { term: 'Kitchen Table Poly', slug: 'kitchen-table-poly', definition: 'Kitchen table poly to styl poliamorii gdzie wszyscy partnerzy i metamourowie znają się, lubią i mogą wspólnie usiąść przy stole kuchennym na kawę i pogadać — bez niezręczności, bez napięcia. Wyobraź sobie: Ty, Twój partner, jego inna partnerka i jej mąż — i wszyscy dobrze się bawicie na wspólnym obiedzie. Nazwa jest trochę idealistyczna, ale całkiem dobrze opisuje intencję: budowanie sieci relacji gdzie wszyscy są ze sobą w jakimś kontakcie. Kitchen table poly nie oznacza że wszyscy muszą być przyjaciółmi na zawsze — chodzi o atmosferę ciepła i otwartości zamiast dyplomatycznego dystansu. Przeciwieństwem jest parallel poly gdzie każda relacja jest osobna i partnerzy nie mają ze sobą kontaktu. Który styl pasuje — to kwestia temperamentu, nie wartości. Oba są ok.', category: 'CNM / Poliamoria', examples: ['W naszej sieci praktykujemy kitchen table poly — wszyscy razem obchodzimy urodziny.'] },
  { term: 'Parallel Poly', slug: 'parallel-poly', definition: 'Parallel poly to styl poliamorii gdzie każda relacja istnieje osobno — partnerzy wiedzą o sobie nawzajem, ale nie mają bezpośredniego kontaktu. Twój partner wie że masz kogoś innego, ale nie zna tej osoby, nie spotykają się, nie ma wspólnych obiadów ani znajomości. To przeciwieństwo kitchen table poly. Dla wielu osób parallel poly jest wygodniejszy — mniej skomplikowanych dynamik grupowych, mniej potencjalnych konfliktów między partnerami. Kryteria: szanuj prywatność każdego z partnerów, nie opowiadaj jednej osobie o drugiej bez zgody, nie porównuj. Parallel poly sprawdza się szczególnie gdy partnerzy mają bardzo różne środowiska i style życia. Ważne: "parallel" nie znaczy "tajne" — wszyscy wiedzą o istnieniu innych, po prostu nie wchodzą w bezpośrednie relacje.', category: 'CNM / Poliamoria', examples: ['Ona i jej mąż preferują parallel poly — każde ma swoje osobne życie.'] },
  { term: 'Solo Poly', slug: 'solo-poly', definition: 'Solo poly to styl poliamorii gdzie osoba świadomie priorytetyzuje własną niezależność i nie szuka "głównego partnera". Każda relacja stoi sama za siebie — bez planu na wspólne mieszkanie, wspólne finanse ani wspinania się po "relationship escalator". Solo poly to nie "jestem singlem co sypia z wieloma osobami" — to świadoma filozofia dotycząca tego jak chcesz budować relacje. Taka osoba może mieć głębokie, długoterminowe związki — po prostu nie szuka kogoś kto będzie "the one". Często wybierana przez osoby które cenią własną przestrzeń, autonomię i nie chcą być zdefiniowane przez swoją relację. Może być błędnie odczytana jako "niedostępna emocjonalnie" — zazwyczaj tak nie jest. To po prostu inny model niż ten który społeczeństwo uznaje za domyślny.', category: 'CNM / Poliamoria', examples: ['Jako solo poly, nie szukam głównego partnera — cenię niezależność i każdy związek traktuję osobno.'] },
  { term: 'Hierarchical Poly', slug: 'hierarchical-poly', definition: 'Hierarchical poly to model w którym relacje są uszeregowane — partner primary ma więcej praw, czasu i priorytetów niż partnerzy secondary. Brzmi zimno, ale dla wielu jest uczciwe i przejrzyste — każdy wie na czym stoi zanim zainwestuje emocjonalnie. Hierarchia może być formalna ("mamy zasadę że partner primary ma prawo weta") albo nieformalna (po prostu tak wychodzi logistycznie bo mieszkacie razem). Krytycy wskazują że secondary partnerzy często czują się jak "opcja B" i cierpią gdy hierarchia jest używana do tłumienia ich potrzeb. Zwolennicy mówią że bez hierarchii trudno chronić istniejące zobowiązania — np. jeśli masz dzieci z partnerem primary. Klucz to transparentność na początku: jeśli ktoś wchodzi w relację wiedząc że jest secondary, mając pełną informację — to inna sytuacja niż gdy odkrywa to po fakcie.', category: 'CNM / Poliamoria', examples: ['W hierarchical poly partner primary może mieć prawo weta przy nowych relacjach.'] },
  { term: 'Non-hierarchical Poly', slug: 'non-hierarchical-poly', definition: 'Non-hierarchical poly to model bez formalnej hierarchii — każda relacja jest ceniona za siebie, nikt nie jest "ważniejszy" z góry. Nie znaczy to że wszystkie relacje są identyczne — naturalnie masz z kimś więcej wspólnego czasu, z kimś innym głębszą więź emocjonalną. Ale nie ma formalnego tytułu który daje jednej osobie "uprawnienia" do decydowania o innych Twoich relacjach. W praktyce bywa wymagające — gdy pojawiają się konflikty, nie ma prostej hierarchii która decyduje "kto ma pierwszeństwo". Wymaga więcej indywidualnych rozmów i negocjacji. Dla wielu jest jednak zdrowsze bo traktuje każdego partnera jako pełnoprawną osobę, nie jako "drugi wybór". Popularny wśród osób które mają złe doświadczenia z hierarchical poly gdzie secondary partnerzy czuli się instrumentalnie traktowani.', category: 'CNM / Poliamoria', examples: ['Preferujemy non-hierarchical poly — każdy związek ma swoją własną wartość.'] },
  { term: 'Relationship Anarchy', slug: 'relationship-anarchy', definition: 'Relationship anarchy (RA) to filozofia odrzucająca sztywne kategorie relacji w ogóle — nie tylko romantycznych. Nie ma wyraźnej granicy między "przyjacielem" a "partnerem", między "romantyczną miłością" a "głęboką przyjaźnią". Każda relacja jest definiowana na własnych warunkach przez osoby w niej uczestniczące, bez presji społecznych skryptów. Termin wymyśliła Szwedka Andie Nordgren w 2006 roku i od tej pory filozofia RA rozrosła się w silny nurt. RA idzie dalej niż polyamoria — to nie jest po prostu "mam wielu partnerów", to fundamentalne kwestionowanie tego czym w ogóle jest relacja. Dla jednych brzmi jak wolność, dla innych jak chaos. W praktyce RA wymaga bardzo dobrej komunikacji i dużej self-awareness — bo skoro nie ma gotowych zasad, wszystko trzeba budować od zera.', category: 'CNM / Poliamoria', examples: ['Relationship anarchy pozwala tworzyć relacje bez presji etykiet i oczekiwań społecznych.'] },
  { term: 'Veto Power', slug: 'veto-power', definition: 'Veto power to prawo jednego partnera do "zawetowania" innej relacji partnera — powiedzenia "nie chcę żebyś spotykał się z tą osobą" i żeby to decydowało. Gorący temat w poly community: jedni uważają veto za niezbędne narzędzie bezpieczeństwa, inni — za kontrolę i naruszenie autonomii partnera. Argument za: pozwala chronić związek primary gdy pojawiają się realne problemy (np. partner zakochuje się w kimś kto go demoralizuje). Argument przeciw: daje jednej osobie władzę nad życiem drugiej, co jest problematyczne. Większość doświadczonych osób w poly odchodzi od formalnego veto na rzecz rozmów o uczuciach i potrzebach — bo "nie możesz się z nią spotykać" to kontrola, a "czuję się niepewnie gdy widzę jak spędzacie czas" to komunikacja. To duża różnica.', category: 'CNM / Poliamoria', examples: ['Zrezygnowaliśmy z veto — wolimy rozmawiać o uczuciach niż używać uprawnień.'] },
  { term: 'Triad', slug: 'triad', definition: 'Triad to związek trzech osób gdzie każda para w grupie jest ze sobą — A kocha B, B kocha C, C kocha A. Wszyscy są ze wszystkimi, tworzą zamkniętą trójkę. To jedna z najbardziej pożądanych konfiguracji w ogłoszeniach CNM i jednocześnie jedna z najtrudniejszych do zbudowania organicznie. Dlaczego trudna? Bo wymaga chemii między trzema parami jednocześnie, kompatybilności trzech różnych charakterów i zazwyczaj mnóstwa negocjacji. Triady które "rosną naturalnie" — gdy trzy osoby zakochują się stopniowo — mają znacznie wyższy wskaźnik sukcesu niż te budowane "z góry" przez parę szukającą trzeciej osoby. To ostatnie to unicorn hunting w innym opakowaniu. Gdy triad działa — jest naprawdę piękny. Gdy nie działa — jest trzy razy więcej emocji.', category: 'CNM / Poliamoria', examples: ['Tworzą triad od trzech lat i wszystkim wychodzi świetnie.'] },
  { term: 'Quad', slug: 'quad', definition: 'Quad to związek czterech osób — zazwyczaj dwie pary gdzie wszyscy są połączeni ze sobą nawzajem. Para A spotyka parę B, zakochują się cross, i nagle masz cztery osoby w sieci wzajemnych relacji. Matematycznie: sześć możliwych par w czterech osobach — każda z tych par to osobna dynamika do zarządzania. To bardzo dużo "moving parts". Gdy działa — quady bywają bardzo stabilne bo masz wbudowany support system. Gdy nie działa — jeden konflikt może destabilizować całą sieć. Quady często zaczynają się od swapowania między parami i ewoluują w głębsze relacje emocjonalne. Wymaga kompatybilności na wielu poziomach jednocześnie: seksualnej, emocjonalnej, życiowej. Rzadkie, ale nie mityczne — istnieją szczęśliwe quady które żyją razem od lat.', category: 'CNM / Poliamoria', examples: ['Quad to cztery osoby tworzące sieć wzajemnych relacji.'] },
  { term: 'V-relationship', slug: 'v-relationship', definition: 'V-relationship to konfiguracja gdzie jedna osoba (zwana hinge) ma dwóch partnerów, którzy nie są ze sobą w relacji. Kształt jak litera V — hinge jest na wierzchołku, dwaj partnerzy na końcach ramion. To jedna z najprostszych i najczęstszych konfiguracji poly. Jeśli jesteś z Anią i z Tomkiem, a Ania i Tomek nie są ze sobą — jesteś hinge w V. Ania i Tomek są swoimi metamourami. Hinge pozycja jest wymagająca — jesteś mostem między dwiema osobami, zarządzasz dwiema relacjami, musisz dbać o to żeby żadna ze stron nie czuła się pominięta. Gdy V jest oparte na parallel poly — partnerzy w ogóle się nie spotykają. Gdy na kitchen table — siedzą razem przy herbacie. Obie opcje działają, zależnie od temperamentu wszystkich zaangażowanych.', category: 'CNM / Poliamoria', examples: ['Ty jesteś z Anią i z Tomkiem, ale Ania i Tomek nie są ze sobą — to V-relationship, Ty jesteś hinge.'] },
  { term: 'Hinge', slug: 'hinge', definition: 'Hinge (zawias) to osoba która jest w centrum V-relationship — ma dwóch (lub więcej) partnerów którzy nie są ze sobą. Słowo pochodzi od zawiasu drzwiowego który łączy dwa skrzydła. Rola hinge bywa piękna i wymagająca jednocześnie. Piękna bo masz dwie głębokie relacje naraz. Wymagająca bo musisz dbać o obie, komunikować się z obiema stronami i pilnować żeby żadna nie czuła się zaniedbana. Częsta pułapka: hinge staje się buforem emocjonalnym gdy partnerzy mają problem z metamourem — i nagle musisz mediować między dwiema osobami które nie rozmawiają ze sobą bezpośrednio. Dobra praktyka: zachęcaj partnerów do bezpośredniej komunikacji gdy to możliwe, zamiast przekazywać wszystko przez siebie. Hinge to nie tłumacz, nie dyplomata i nie terapeuta — przynajmniej nie powinien być.', category: 'CNM / Poliamoria', examples: ['Jako hinge masz odpowiedzialność wobec obojga partnerów — wymagające, ale satysfakcjonujące.'] },
  { term: 'Cowboy / Cowgirl', slug: 'cowboy-cowgirl', definition: 'Cowboy albo cowgirl to osoba która świadomie wchodzi w relację z kimś poly z zamiarem "zabrania ich ze sceny" — czyli stopniowego przekonania ich do monogamii wyłącznie z sobą. Metafora pochodzi od "wranglowania" — ujarzmienia kogoś jak dzikiego konia. Brzmi romantycznie tylko z jednej strony. Dla osoby poly często jest to zdrada zaufania — wchodzisz w relację wiedząc o ich lifestyle, a potem systematycznie podważasz go. Red flags: "czy naprawdę potrzebujesz innych?", "może jesteś poly tylko bo nie spotkałeś jeszcze właściwej osoby", naciski na rezygnację z innych relacji. Nie każda osoba mono zakochana w kimś poly to cowboy — różnica jest w intencji. Zdrowa wersja: szczera rozmowa o tym że chcesz monogamii i zostawienie drugiej osobie wyboru bez manipulacji.', category: 'CNM / Poliamoria', examples: ['Spotykasz się z kimś kto wie że jesteś poly, ale mówi "zakochasz się i zostawisz innych".'] },
  { term: 'Couple Privilege', slug: 'couple-privilege', definition: 'Couple privilege to nieuświadomiona (lub świadoma) przewaga jaką istniejąca para ma nad innymi partnerami w układzie poly. Mieszkają razem, mają wspólne finanse, decydują o ważnych sprawach razem — a inni partnerzy mają się dostosować do ich rozkładu, zasad i preferencji. Brzmi znajomo? Bo to trochę jak biały przywilej ale w relacjach. Para nie zawsze zdaje sobie sprawę że to robi. Objawy: "nasze zasady", "my zdecydujemy czy możesz się z nimi spotykać", "masz się dopasować do naszego harmonogramu". Nie chodzi o to że para nie może mieć wspólnych ustaleń — chodzi o to gdy te ustalenia jednostronnie ograniczają autonomię innych partnerów bez uwzględnienia ich potrzeb. Remedium: regularne pytanie "jak to wygląda z Twojej perspektywy?" skierowane do wszystkich stron.', category: 'CNM / Poliamoria', examples: ['Couple privilege pojawia się gdy para traktuje swój związek jako ważniejszy od wszystkich innych.'] },
  { term: 'Relationship Escalator', slug: 'relationship-escalator', definition: 'Relationship escalator to metafora ruchomych schodów — społeczny skrypt który mówi jak "powinien" wyglądać związek: randkowanie → wyłączność → zamieszkanie → zaręczyny → ślub → dzieci → koniec. Każdy krok prowadzi do następnego, zatrzymanie się jest podejrzane, cofnięcie się to "problem". W CNM i poly wiele osób świadomie z tych schodów schodzi — bo może chcesz głębokiej relacji bez zamieszkiwania razem, albo chcesz mieszkać razem bez ślubu, albo chcesz w ogóle definiować to co macie po swojemu. "Stepping off the escalator" to popularny termin na świadome odejście od tego skryptu. Warto wiedzieć że escalator nie jest złem wcielonym — dla wielu jest świetny. Problem pojawia się gdy traktujesz go jako jedyną możliwą drogę i oceniasz innych przez jego pryzmat.', category: 'CNM / Poliamoria', examples: ['W CNM związek może być głęboki i wartościowy bez "wspinania się" po schodach ruchomych.'] },
  { term: 'OPP (One Penis Policy)', slug: 'one-penis-policy', definition: 'OPP to zasada w parze hetero gdzie mężczyzna "pozwala" partnerce spotykać się z kobietami, ale nie z innymi mężczyznami. On może albo nie może spotykać się z innymi — zależy od konkretnej pary. Powszechnie krytykowana w środowisku CNM z kilku powodów naraz. Po pierwsze: traktuje partnerkę jak własność ("pozwalam ci"). Po drugie: deprecjonuje jej relacje z kobietami jako mniej poważne lub niezagrażające. Po trzecie: zazwyczaj wynika z insecurity mężczyzny a nie z przemyślanego modelu. Po czwarte: jest seksistowska bo zakłada że kobiety są "bezpieczne" a mężczyźni — zagrożeniem. Jeśli naprawdę chcesz otwartego związku, warto zadać sobie pytanie: skąd pochodzi ten strach i czy da się przepracować go inaczej niż przez zasadę?', category: 'CNM / Poliamoria', examples: ['OPP jest krytykowana za to że traktuje partnerkę jak własność i deprecjonuje jej relacje z kobietami.'] },
  { term: 'DADT (Don\'t Ask, Don\'t Tell)', slug: 'dadt', definition: 'DADT to typ otwartego związku gdzie partnerzy mogą mieć seks z innymi osobami, ale nie mówią sobie o tym — ani nie pytają. "Co się dzieje poza nami, zostaje poza nami." Nazwa pochodzi od kontrowersyjnej polityki US Army wobec homoseksualnych żołnierzy — tutaj używana bez tego kontekstu, czysto opisowo. Dla niektórych par DADT działa świetnie: chcą wolności ale nie chcą szczegółów które wywołują zazdrość lub dyskomfort. Dla innych jest to forma zaprzeczenia — udajemy że to się nie dzieje, choć oboje wiemy że się dzieje. Krytycy mówią że DADT uniemożliwia prawdziwą rozmowę o granicach, testach na STI i emocjach. Zwolennicy mówią że to świadomy wybór pary i każdy ma prawo do swojego modelu. Jak zawsze: jeśli oboje zgadzacie się w pełni świadomie — Wasza sprawa.', category: 'CNM / Poliamoria', examples: ['DADT działa dla niektórych par, ale bywa krytykowane za brak transparency.'] },
  { term: 'Fluid Bonding', slug: 'fluid-bonding', definition: 'Fluid bonding to świadoma decyzja o uprawianiu seksu bez prezerwatyw z konkretnym partnerem — zazwyczaj po wzajemnych testach na STI i po ustaleniu co robią z innymi partnerami. "Fluid" odnosi się do płynów ustrojowych. To nie jest tylko kwestia wygody czy przyjemności — to akt zaufania i intymności, szczególnie w środowisku CNM gdzie masz kilku partnerów. Warunki dobrego fluid bondingu: oboje zrobiliście testy, znacie wyniki, ustaliliście jakich zasad przestrzegacie z innymi partnerami (np. zawsze kondom z nowymi osobami), regularnie powtarzacie testy. Fluid bonding z jedną osobą to zobowiązanie które wpływa na wszystkich innych Twoich partnerów — dlatego warto omówić to ze wszystkimi zainteresowanymi, nie tylko z daną osobą. To jeden z tych tematów gdzie transparentność dosłownie chroni zdrowie.', category: 'CNM / Poliamoria', examples: ['Fluid bonding wymaga wzajemnego zaufania i regularnych testów — nie robi się tego z nową osobą.'] },
  { term: 'Poly-Saturated', slug: 'poly-saturated', definition: 'Poly-saturated to stan w którym masz już tyle relacji ile jesteś w stanie zdrowo podtrzymywać — emocjonalnie, czasowo, energetycznie. Jesteś "pełny". Nie ma już miejsca na nową relację bez zaniedbania istniejących. Termin jest całkowicie neutralny — to nie jest wada ani cnota, to po prostu obserwacja swoich możliwości. Każdy ma inną pojemność: niektórzy czują się poly-saturated przy dwóch partnerach, inni przy pięciu. Zależy od intensywności relacji, Twojego temperamentu, sytuacji życiowej i ile czasu masz po pracy i śnie. Ważna umiejętność: rozpoznać że jesteś poly-saturated ZANIM zaczniesz nową relację i zawieść kogoś kto na Ciebie liczył. Mówienie "nie mam teraz miejsca na nową relację" to uczciwe i dojrzałe — nie każdy musi wieczne szukać nowych połączeń.', category: 'CNM / Poliamoria', examples: ['Jestem teraz poly-saturated — trzy relacje to moje maksimum.'] },
  { term: 'Mononormatywność', slug: 'mononormatywnosc', definition: 'Mononormatywność to założenie wbudowane w kulturę że monogamia jest domyślna, naturalna i jedyna właściwa forma związku — a wszystko inne jest dziwne, niezdrowe lub przejściowe. Przejawia się w pytaniach typu "kiedy się w końcu ustatkujesz?", "nie boisz się że Cię zdradzi?", "ale kogo tak naprawdę bardziej kochasz?" albo w tym że formularze mają pole tylko na jednego partnera/małżonka. Mononormatywność nie jest złośliwa — większość ludzi po prostu powtarza to czego się nauczyli. Ale dla osób w CNM czy poly bywa wyczerpująca: ciągłe tłumaczenie, ukrywanie, lub zderzanie się z niezrozumieniem. Świadomość mononormatywności nie oznacza że musisz nawracać każdego monogamisty — monogamia jest ok. Chodzi o to żeby żaden model nie był traktowany jako jedyny możliwy.', category: 'CNM / Poliamoria', examples: ['"Kiedy się w końcu ustatkujesz?", "Takie związki się nie udają" — przykłady mononormatywnych komentarzy.'] },
  { term: 'Monogamish', slug: 'monogamish', definition: 'Monogamish to związek który jest w zasadzie monogamiczny ale z ustalonymi wyjątkami — para jest razem, jest ich "głównym" układem, ale od czasu do czasu, na ustalonych zasadach, mogą mieć doświadczenia z innymi. Termin wymyślił Dan Savage, seksuolog i publicysta, opisując swój własny związek. Monogamish jest gdzieś na continuum między monogamią a otwartym związkiem — bliżej monogamii. Wyjątki mogą być rzadkie (raz w roku na urlopie) lub częstsze, seksualne bez emocji, mogą angażować oboje partnerów naraz lub osobno. Kluczowe: "ish" — "prawie". To nie jest otwarta poliamoria, to nie jest full swinging, to po prostu mała elastyczność w ramach silnego, stabilnego związku. Dla wielu par to idealne rozwiązanie które pozwala mieć i ciągłość, i odrobinę przygody.', category: 'CNM / Poliamoria', examples: ['Jesteśmy monogamish — czasem mamy przygody, ale zawsze razem o tym decydujemy.'] },
  { term: 'De-escalate', slug: 'de-escalate', definition: 'De-escalate to świadome zmniejszenie intensywności lub zakresu relacji — bez jej kończenia. Przykłady: przestajecie mieszkać razem ale dalej jesteście parą, rezygnujecie z planów wspólnej przyszłości ale zostajecie ważnymi osobami w swoim życiu, ograniczacie częstotliwość spotkań. To przeciwieństwo "relationship escalator" — zamiast ciągłego "wchodzenia wyżej", czasem lepiej jest zejść o poziom. De-escalation bywa odbierana jako "porażka" lub "rozpad związku" — szczególnie przez osoby z zewnątrz. W rzeczywistości często ratuje relację i czyni ją zdrowszą. Para która ze wspólnego mieszkania wraca do osobnych, ale spotyka się regularnie i jest szczęśliwa — to sukces, nie porażka. W CNM de-escalation jest narzędziem, nie klęską.', category: 'CNM / Poliamoria', examples: ['Zdecydowaliśmy się de-escalować — teraz mieszkamy osobno, ale relacja jest zdrowsza.'] },
  { term: 'Check-in', slug: 'check-in', definition: 'Check-in to regularna, zaplanowana rozmowa z partnerem o stanie waszej relacji — jak się czujecie, czy są jakieś niezaspokojone potrzeby, co działa dobrze a co można poprawić. W CNM check-iny są szczególnie ważne bo masz więcej "moving parts" — więcej osób, więcej emocji, więcej potencjalnych nieporozumień. Dobry check-in to nie kłótnia i nie przesłuchanie — to bezpieczna przestrzeń na powiedzenie "ostatnio czuję się trochę pominięta" albo "chciałbym żebyśmy spędzali więcej czasu sami". Częstotliwość: co tydzień lub co dwa tygodnie to dobry rytm dla par w aktywnym CNM. Format: możecie mieć konkretne pytania które zawsze zadajecie sobie nawzajem ("jak się czujesz na skali 1-10?", "czy jest coś o czym chciałeś porozmawiać?"). Check-in to nawyk który oszczędza wiele małych i dużych kryzysów zanim te w ogóle wybuchną.', category: 'CNM / Poliamoria', examples: ['Co tydzień mamy check-in — 30 minut tylko na rozmowę o nas.'] },
  { term: 'FWB (Friends with Benefits)', slug: 'fwb', definition: 'FWB, czyli przyjaciele z korzyściami, to relacja między ludźmi którzy się lubią, przyjaźnią, ale też uprawiają ze sobą seks — bez romantycznego zaangażowania i bez etykiety "para". "No strings attached" — bez zobowiązań. W kontekście CNM FWB to jedna z wielu możliwych konfiguracji: masz głównych partnerów i kilka FWB z którymi spotykasz się okazjonalnie. Brzmi prosto, w praktyce bywa skomplikowane: jedno z was może z czasem chcieć czegoś więcej, albo odwrotnie — jeden z was chce zakończyć seksualny aspekt ale zachować przyjaźń. Klucz do zdrowego FWB: rozmowa o oczekiwaniach na początku i regularne upewnianie się że oboje nadal chcecie tego co macie. "No strings" nie znaczy "zero komunikacji" — znaczy "brak romantycznych zobowiązań".', category: 'CNM / Poliamoria', examples: ['Mamy FWB — lubimy się, spędzamy czas, ale żadne z nas nie chce "czegoś więcej".'] },
  { term: 'Comet', slug: 'comet', definition: 'Comet to partner z którym spotykasz się rzadko — może kilka razy w roku, może przy okazji podróży albo konferencji — ale relacja jest intensywna i wartościowa mimo rzadkości kontaktu. Jak kometa: pojawia się nieregularnie, ale gdy jest — jest jasna i wyraźna. Comet relationships są szczególnie popularne wśród osób które dużo podróżują lub mają rozproszonych geograficznie znajomych w środowisku lifestyle. Nie ma tu presji codziennego kontaktu ani regularnych randek — relacja żyje własnym rytmem. Może być seksualna, romantyczna, albo jedno i drugie. Wymaga akceptacji że ta osoba nie będzie "dostępna" na co dzień — i że to jest ok. Dla niektórych comet jest idealną formą bo daje intensywność bez logistyki długoterminowej relacji.', category: 'CNM / Poliamoria', examples: ['On jest moim comet — widzimy się 3-4 razy w roku, ale to ważna relacja.'] },
  { term: 'Ethical Slut', slug: 'ethical-slut', definition: '"The Ethical Slut" to tytuł kultowej książki Dossie Easton i Janet Hardy z 1997 roku — i zarazem termin który autorki świadomie "odzyskały" ze słownika obraźliwego. Ethical slut to osoba świadomie i etycznie aktywna seksualnie z wieloma partnerami — ktoś kto lubi seks, ma wielu partnerów, i robi to w sposób uczciwy, z szacunkiem i za zgodą wszystkich zaangażowanych. "Slut" (suka, puszczalska) w tym kontekście jest użyte z dumą i humorem — jako odpowiedź na kulturę która stygmatyzuje seksualną aktywność, szczególnie kobiet. Książka to lektura obowiązkowa dla każdego zaczynającego przygodę z CNM — nie tylko dlatego że definiuje pojęcia, ale dlatego że ma ciepły, nieoceniający, praktyczny głos. Jeśli czytasz jeden rozdział — przeczytaj ten o zazdrości.', category: 'CNM / Poliamoria', examples: ['"The Ethical Slut" to lektura obowiązkowa dla każdego zaczynającego w CNM.'] },

  // === SWINGING / LIFESTYLE ===
  { term: 'Swinging', slug: 'swinging', definition: 'Swinging to styl życia w którym pary — najczęściej heteroseksualne, choć nie wyłącznie — konsensualnie wymieniają się partnerami seksualnymi lub uczestniczą razem w grupowych aktywnościach seksualnych. Kluczowa różnica wobec poliamории: swinging koncentruje się na seksie, nie na budowaniu głębokich więzi emocjonalnych z innymi osobami. Para pozostaje parą, seks z innymi to wspólna przygoda, nie zagrożenie. Swinging ma długą historię — jego złoty wiek to lata 70. w USA, ale praktykowany był znacznie wcześniej. W Polsce scena jest aktywna i dyskretna — lifestyle cluby działają w Warszawie, Krakowie, Łodzi, Poznaniu i innych miastach. Motywacje par są różne: ciekawość, odświeżenie pożycia, wspólna przygoda, voyeuryzm, ekshibicjonizm. Najważniejsza zasada: oboje muszą chcieć — jeśli jedno z was jest "przekonywane", to zły znak.', category: 'Swinging / Lifestyle', examples: ['Para od lat praktykuje swinging w zamkniętym kręgu zaufanych przyjaciół.'] },
  { term: 'The Lifestyle', slug: 'the-lifestyle', definition: '"The Lifestyle" to tak swinging community mówi o sobie i swojej scenie — dyskretnie, bez wprost nazywania tego swingingiem. "Czy jesteście w lifestyle?" to pytanie które usłyszysz na imprezie lub portalu i które znaczy dokładnie tyle ile myślisz. Termin parasolowy dla całego środowiska: par, singli, klubów, eventów, forów. Ma w sobie coś eleganckiego — nie "sex party", nie "orgia", po prostu "lifestyle". Używany głównie w kontekście angielskim, ale w Polsce coraz powszechniejszy. Jeśli ktoś pyta czy jesteś "w lifestyle" — upewnij się że oboje partnerzy są świadomi pytania i odpowiadacie razem.', category: 'Swinging / Lifestyle', examples: ['"Jesteśmy w lifestyle od 3 lat" — czyli od 3 lat aktywnie uczestniczą w swinger scene.'] },
  { term: 'Soft Swap', slug: 'soft-swap', definition: 'Soft swap to wymiana partnerów z ograniczonym kontaktem seksualnym — całowanie, dotykanie, oral sex są ok, ale penetracja — nie. Idealne dla par które dopiero zaczynają eksplorować swinging i chcą poczuć jak to jest, zanim zdecydują się na więcej. Ale też dla par które po prostu mają taką granicę na stałe i im tak odpowiada — i to jest w pełni ok. Soft swap pozwala doświadczyć bliskości z inną osobą przy zachowaniu pewnego "ostatniego progu" tylko dla siebie nawzajem. Wiele par pozostaje na poziomie soft swap przez lata i jest z tego zadowolona. Ważne: soft swap z jedną parą nie zobowiązuje Cię do niczego z kolejną — każda interakcja jest osobną decyzją.', category: 'Swinging / Lifestyle', examples: ['Zaczęliśmy od soft swap żeby poczuć jak to jest, zanim zdecydujemy się na więcej.'] },
  { term: 'Full Swap', slug: 'full-swap', definition: 'Full swap to pełna wymiana partnerów — wszystkie aktywności seksualne włącznie z penetracją są ok. Dla wielu par to naturalna ewolucja po soft swappingu, dla innych punkt startowy. Full swap wymaga wyższego poziomu zaufania i komunikacji w parze — przed, w trakcie i po. Przed: upewnijcie się że oboje naprawdę tego chcecie, nie tylko że jedno jest "ok" z tym żeby zadowolić drugie. W trakcie: sprawdzajcie się nawzajem, szczególnie na początku. Po: porozmawiajcie o tym jak się czujecie — zarówno jeśli było super, jak i jeśli pojawiły się nieprzewidziane emocje. Full swap może być świetnym doświadczeniem; może też ujawnić uczucia na które nie byliście gotowi. Obie opcje są do zarządzenia jeśli macie dobry kontakt.', category: 'Swinging / Lifestyle', examples: ['Para zdecydowała się na full swap po roku soft swappingu.'] },
  { term: 'Same Room', slug: 'same-room', definition: 'Same room to swap gdzie wszystkie pary pozostają w tym samym pokoju i widzą się nawzajem podczas zabawy. Dla wielu par to preferowana opcja szczególnie na początku — możesz mieć kontakt wzrokowy z partnerem, czuć jego obecność, widzieć że wszystko jest ok. Same room daje poczucie wspólnoty i wspólnej przygody zamiast "każdy osobno gdzieś". Voyeurystyczny aspekt patrzenia na partnera z kimś innym bywa dla wielu silnie podniecający. Same room nie znaczy że musisz cały czas patrzeć — po prostu wszyscy są w tej samej przestrzeni. Dla newbies same room jest zazwyczaj bezpieczniejszym punktem startowym niż separate room.', category: 'Swinging / Lifestyle', examples: ['Same room pozwala pozostać w kontakcie wzrokowym z partnerem podczas zabawy.'] },
  { term: 'Separate Room', slug: 'separate-room', definition: 'Separate room to opcja gdzie pary idą do osobnych pokoi — nie widzisz co Twój partner robi i on nie widzi Ciebie. Pełna prywatność z drugą parą. Wymaga znacznie wyższego poziomu zaufania i komfortu — nie ma wzrokowego "sprawdzania" partnera, musisz być ok z tym że nie wiesz dokładnie co się dzieje. Dla doświadczonych par separate room bywa bardziej intensywnym i swobodniejszym doświadczeniem — możesz w pełni skupić się na drugiej osobie bez myślenia o tym co widzi partner. Jeśli rozważasz separate room po raz pierwszy — porozmawiajcie wcześniej o tym jak się będziecie czuć i ustalcie co się dzieje po — np. spotykacie się w barze po godzinie.', category: 'Swinging / Lifestyle', examples: ['Po roku w lifestyle zdecydowali się na separate room — wzajemne zaufanie jest na to gotowe.'] },
  { term: 'Hotwife', slug: 'hotwife', definition: 'Hotwife to żona (lub stała partnerka) która uprawia seks z innymi mężczyznami — i czasem kobietami — za pełną wiedzą i zgodą swojego partnera. Kluczowy element: focus na przyjemności i seksualnej wolności kobiety, z mężem jako aktywnym, dumnym uczestnikiem tej dynamiki — nawet jeśli sam nie śpi z innymi. Hotwife różni się od zwykłego otwartego związku przede wszystkim klimatem: to nie "oboje możemy" ale "ona może i oboje to celebrujemy". Mąż (zwany czasem stag) czerpie podniecenie z sukcesu seksualnego żony, jej atrakcyjności dla innych mężczyzn, z opowieści lub obserwowania. Hotwifing wymaga bardzo dobrej komunikacji i pewności siebie po obu stronach. Nie jest synonimem cuckolding — hotwifing jest pozbawiony elementu upokorzenia, to celebration, nie humiliation.', category: 'Swinging / Lifestyle', examples: ['W hotwifing chodzi o wolność i spełnienie kobiety — mąż z dumą i podnieceniem wspiera jej przygody.'] },
  { term: 'Cuckold / Cuckolding', slug: 'cuckolding', definition: 'Cuckolding to dynamika w której mąż lub partner (cuckold) czerpie podniecenie z tego że jego żona uprawia seks z innym mężczyzną — zwanym bull. W odróżnieniu od hotwifing, cuckolding często zawiera element psychologicznego upokorzenia: bull jest przedstawiany jako "lepszy", silniejszy, bardziej atrakcyjny, a mąż jako "niewystarczający". To świadoma, negocjowana gra erotyczna — nie rzeczywiste upokorzenie wbrew woli. Cuckold może być obecny i obserwować, słyszeć o tym po fakcie, albo być aktywnie wykluczany jako część fantazji. Cuckolding jest jedną z najpopularniejszych fantazji seksualnych wśród mężczyzn i istnieje od wieków — literatura erotyczna pełna jest tych motywów. Kluczowa zasada jak zawsze: wszystko jest negocjowane i za zgodą wszystkich stron.', category: 'Swinging / Lifestyle', examples: ['Cuckolding to świadoma gra z dominacją i uległością — kluczowa jest zgoda i negocjacja.'] },
  { term: 'Bull', slug: 'bull', definition: 'Bull to mężczyzna który uprawia seks z hotwife lub partnerką cuckold. Stereotypowo bywa opisywany jako pewny siebie, dominujący, fizycznie imponujący — ale to przede wszystkim rola w fantazji, nie wymóg. W praktyce bull to po prostu mężczyzna który wszedł w tę dynamikę ze świadomością swojej roli. Bull zazwyczaj ma relację seksualną z kobietą, rzadziej bezpośredni kontakt z jej partnerem — choć w zależności od pary układy bywają różne. Dobry bull rozumie że wchodzi w czyjś związek i zachowuje się z szacunkiem wobec obojga partnerów, nie tylko tej z którą śpi. Bycie bullem to odpowiedzialność — nie tylko przywilej.', category: 'Swinging / Lifestyle', examples: ['Bull w hotwifing jest partnerem żony — zazwyczaj nie ma relacji z mężem.'] },
  { term: 'Stag / Vixen', slug: 'stag-vixen', definition: 'Stag/vixen to dynamika podobna do hotwife/cuckolding, ale z jedną kluczową różnicą: brak elementu upokorzenia. Stag (jeleń) to partner który z dumą i podnieceniem obserwuje lub wie o przygodach vixen (lisicy) — bez żadnej narracji o byciu "niewystarczającym". Vixen cieszy się wolnością seksualną, stag cieszy się jej sukcesem i seksualnością. To czysta celebracja, nie gra ze wstydem. Dla par które przyciąga hotwifing ale odpycha humiliation dynamic — stag/vixen jest naturalnym wyborem. Stag może być aktywnie zaangażowany (obserwuje, rozmawia z bullem, planuje z żoną) albo bardziej z dystansu — każda para definiuje swoje granice. Zdrowa dynamika stag/vixen opiera się na wzajemnym szacunku i entuzjazmie obojga.', category: 'Swinging / Lifestyle', examples: ['Stag/vixen to dla par które chcą seksualnej wolności bez humiliation dynamics.'] },
  { term: 'MFM / MMF', slug: 'mfm-mmf', definition: 'Threesome z kobietą i dwoma mężczyznami. MFM = mężczyźni nie mają kontaktu ze sobą (focus on woman). MMF = mężczyźni też się bawią ze sobą (bi).', category: 'Swinging / Lifestyle', examples: ['Para szuka partnera do MFM — obu mężczyzn interesuje wyłącznie kobieta.'] },
  { term: 'FMF / FFM', slug: 'fmf-ffm', definition: 'Threesome z mężczyzną i dwiema kobietami. FMF = kobiety nie mają kontaktu ze sobą. FFM = kobiety też się bawią ze sobą (bi/bi-curious).', category: 'Swinging / Lifestyle', examples: ['Para szuka kobiety do FFM — obydwie kobiety są bi.'] },
  { term: 'Gang Bang', slug: 'gang-bang', definition: 'Jedna osoba (zazwyczaj kobieta) uprawia seks z wieloma partnerami (zazwyczaj mężczyznami) jednocześnie lub po kolei.', category: 'Swinging / Lifestyle', examples: ['Gang bang to jeden z typowych tematycznych eventów w klubach swingerskich.'] },
  { term: 'Reverse Gang Bang', slug: 'reverse-gang-bang', definition: 'Jeden mężczyzna uprawia seks z wieloma kobietami jednocześnie lub po kolei. Rzadsze niż klasyczny gang bang.', category: 'Swinging / Lifestyle', examples: ['Reverse gang bang pojawia się rzadziej, ale jest organizowany na specjalnych imprezach.'] },
  { term: 'Train', slug: 'train', definition: 'Osoba uprawia seks z wieloma partnerami, ale kolejno (nie jednocześnie). W kolejce.', category: 'Swinging / Lifestyle', examples: ['Train różni się od orgy — tutaj chodzi o kolejność, nie o jednoczesność.'] },
  { term: 'Orgy / Group Play', slug: 'orgy', definition: 'Seks z wieloma osobami jednocześnie (5+). Może być zorganizowany (w klubie) lub spontaniczny.', category: 'Swinging / Lifestyle', examples: ['Orgy w lifestyle clubie odbywa się w specjalnie wyposażonych salach.'] },
  { term: 'Voyeur', slug: 'voyeur', definition: 'Osoba która lubi patrzeć jak inni uprawiają seks. Podnieta ze spektatorstwa.', category: 'Swinging / Lifestyle', examples: ['Wiele lifestyle clubs ma specjalne voyeur rooms — możesz patrzeć, ale nie dołączać.'] },
  { term: 'Exhibitionista', slug: 'exhibicjonista', definition: 'Osoba która lubi być oglądana podczas seksu. Podnieta z bycia obserwowanym.', category: 'Swinging / Lifestyle', examples: ['W lifestyle clubs exhibitioniści mogą bawić się w open playrooms.'] },
  { term: 'Hall Pass', slug: 'hall-pass', definition: 'Pozwolenie od partnera żeby uprawiać seks z kimś innym solo, bez obecności partnera. "Przepustka" na randkę poza główną parą.', category: 'Swinging / Lifestyle', examples: ['"Mam hall pass na ten weekend" — mogę się spotkać z kimś solo.'] },
  { term: 'Playroom', slug: 'playroom', definition: 'Pokój w lifestyle club wyposażony do seksu. Może być public (otwarty na patrzenie), private (zamknięty) lub semi-private.', category: 'Swinging / Lifestyle', examples: ['Public playroom pozwala innym patrzeć, private daje pełną prywatność.'] },
  { term: 'Dress Code', slug: 'dress-code', definition: 'Zasady ubioru w lifestyle club. Zazwyczaj: mężczyźni — spodnie i koszula, bez trampek; kobiety — sukienka, bielizna, obcasy. Po północy często "only towels" lub lingerie.', category: 'Swinging / Lifestyle', examples: ['Dress code w lifestyle klubach jest zazwyczaj seksowny ale elegancki — nie przychodzi się w dżinsach i t-shircie.'] },
  { term: 'Newbies', slug: 'newbies', definition: 'Para lub osoba która dopiero zaczyna w lifestyle. Nowi, często nervous, z dużą ilością pytań, eksplorujący swoje granice.', category: 'Swinging / Lifestyle', examples: ['Jako newbies zaczęliśmy od Meet & Greet zanim zdecydowaliśmy się na wizytę w klubie.'] },
  { term: 'Discretion', slug: 'discretion', definition: 'Zachowanie lifestyle w tajemnicy przed "vanilla" życiem — pracą, rodziną, znajomymi. Zasady: brak zdjęć bez zgody, nie ujawnianie danych osobowych, "co się dzieje w klubie, zostaje w klubie".', category: 'Swinging / Lifestyle', examples: ['Discretion to podstawa — wiele osób nie chce być "outed" w swoim środowisku zawodowym.'] },
  { term: 'Verify / Weryfikacja', slug: 'weryfikacja', definition: 'Potwierdzenie że profil na portalu lifestyle jest prawdziwy. Zazwyczaj przez video call lub spotkanie. Ważne bo dużo fake profiles online.', category: 'Swinging / Lifestyle', examples: ['Zanim się spotkamy, prosimy o weryfikację video — to standard w naszym środowisku.'] },
  { term: 'Chemistry', slug: 'chemistry', definition: 'Wzajemna atrakcja między parami. Musi być żeby zagrać. "No chemistry" to grzeczna odmowa — nic złego, po prostu nie ma flow.', category: 'Swinging / Lifestyle', examples: ['"Nie ma chemii" — polite way to decline. Doesn\'t mean anything is wrong.'] },
  { term: 'Reclaim Sex', slug: 'reclaim-sex', definition: 'Seks z Twoim partnerem PO zabawie z innymi. Reconnecting, potwierdzenie waszego związku. Bardzo powszechne — pary wracają do siebie po sesji.', category: 'Swinging / Lifestyle', examples: ['Po każdej imprezie lifestyle zawsze mamy swój czas — reclaim sex jest ważną częścią naszego rytuału.'] },
  { term: 'GGG (Good, Giving, Game)', slug: 'ggg', definition: 'Filozofia od Dana Savage. Bądź: Good (dobry w łóżku), Giving (dbaj o potrzeby partnera), Game (otwarty na nowe rzeczy w granicach rozsądku).', category: 'Swinging / Lifestyle', examples: ['GGG to postawa którą ceni lifestyle community — wzajemność i otwartość.'] },
  { term: 'Meet & Greet', slug: 'meet-and-greet', definition: 'Casualowe spotkanie towarzyskie dla ludzi z lifestyle community w publicznym miejscu (kawiarnia, restauracja). Bez seksu, tylko poznawanie. Świetne dla newbies.', category: 'Swinging / Lifestyle', examples: ['Zaczęliśmy od Meet & Greet — pozwoliło nam poznać kilka par przed pójściem do klubu.'] },
  { term: 'Hotel Takeover', slug: 'hotel-takeover', definition: 'Impreza gdzie lifestyle group rezerwuje większość pokoi w hotelu na weekend. Prywatne parties, pool parties, etc. Całość jest dla swingers.', category: 'Swinging / Lifestyle', examples: ['Hotel takeover to intensywniejsze doświadczenie niż klub — cały weekend w jednym miejscu.'] },
  { term: 'House Party', slug: 'house-party', definition: 'Lifestyle party zorganizowane w czyimś domu. Zazwyczaj tylko na zaproszenie, sprawdzone osoby. Bardziej intymne niż klub.', category: 'Swinging / Lifestyle', examples: ['House party są kameralne i przyjazne — znasz prawie każdego.'] },
  { term: 'Lifestyle Friendly', slug: 'lifestyle-friendly', definition: 'Hotel, resort lub lokal który jest ok z lifestyle gośćmi — nie wyrzuci Cię za PDAs lub wiele osób w pokoju.', category: 'Swinging / Lifestyle', examples: ['Szukamy lifestyle friendly hotelu na weekend — potrzebujemy swobody.'] },
  { term: 'On-premise', slug: 'on-premise', definition: 'Wydarzenie lub klub gdzie aktywność seksualna ma miejsce na miejscu. Jest specjalna strefa zabaw.', category: 'Swinging / Lifestyle', examples: ['To on-premise event — jest specjalna strefa play na piętrze.'] },
  { term: 'Off-premise', slug: 'off-premise', definition: 'Wydarzenie towarzyskie BEZ aktywności seksualnej na miejscu. Flirty ok, seks — umów się prywatnie.', category: 'Swinging / Lifestyle', examples: ['To off-premise party — Meet & Greet, poznajemy się, a potem każdy układa się osobno.'] },
  { term: 'No Means No', slug: 'no-means-no', definition: 'Zero tolerance policy. Jeśli ktoś mówi "nie" — natychmiastowe stop. Brak negocjacji. Naruszenie = stałe wyrzucenie z klubu.', category: 'Swinging / Lifestyle', examples: ['No means no to absolutna zasada w lifestyle community — szanujemy granice zawsze.'] },
  { term: 'Lifestyle Club / Swinger Club', slug: 'lifestyle-club', definition: 'Klub gdzie pary (i czasem single) spotykają się żeby uprawiać seks. Zazwyczaj: bar/lounge, dance floor, playrooms, jacuzzi/sauna. W Polsce: Lava, Elysium, Jacuzzi Club, Heaven, Bordeaux.', category: 'Swinging / Lifestyle', examples: ['Lifestyle club to bezpieczna przestrzeń gdzie wszystko odbywa się za zgodą i w dyskrecji.'] },
  { term: 'Single Female (SF)', slug: 'single-female', definition: 'Kobieta single w lifestyle scene. Bardzo mile widziane, często wchodzą za free lub po niższej cenie. Popyt jest wyższy niż podaż.', category: 'Swinging / Lifestyle', examples: ['Single female zawsze są mile widziane w lifestyle clubs.'] },
  { term: 'Single Male (SM)', slug: 'single-male', definition: 'Mężczyzna single w lifestyle scene. Trudniej dostać się na eventy — wyższe ceny, limitowane miejsca. Bo jest znacznie więcej chętnych mężczyzn niż miejsc.', category: 'Swinging / Lifestyle', examples: ['Dla single male lifestyle scene jest trudniejsza — wiele klubów ma limit lub wyższe ceny.'] },

  // === BDSM / KINK ===
  { term: 'BDSM', slug: 'bdsm', definition: 'Umbrella term obejmujący: B&D (Bondage & Discipline — wiązanie i dyscyplina), D/s (Dominance & Submission — dominacja i uległość), S&M (Sadism & Masochism — sadyzm i masochizm).', category: 'BDSM / Kink', examples: ['BDSM wymaga dokładnego omówienia granic przed każdą sesją.'] },
  { term: 'Kink', slug: 'kink', definition: 'Wszystko co wykracza poza "vanilla sex". Szersze niż BDSM — obejmuje fetisze, role play i inne niestandardowe praktyki. Przykłady: impact play, rope bondage, age play, pet play.', category: 'BDSM / Kink', examples: ['Każdy ma swoje kinki — ważne żeby omówić je z partnerem.'] },
  { term: 'Safeword', slug: 'safeword', definition: 'Umówione słowo lub sygnał służące do natychmiastowego przerwania aktywności BDSM. Używając safeword — wszystko się zatrzymuje. Brak dyskusji, brak negocjacji.', category: 'BDSM / Kink', examples: ['Naszym safeword jest "ananasy" — jak tylko je powie, wszystko zatrzymujemy.'] },
  { term: 'Red / Yellow / Green', slug: 'red-yellow-green', definition: 'Popularny system safeword: Red = stop natychmiast, Yellow = zwolnij / muszę porozmawiać, Green = wszystko ok, dalej.', category: 'BDSM / Kink', examples: ['Używamy systemu Red/Yellow/Green — Yellow nie znaczy stop, tylko "daj mi chwilę".'] },
  { term: 'SSC (Safe, Sane, Consensual)', slug: 'ssc', definition: 'Filozofia BDSM: wszystko powinno być Bezpieczne (minimalizujesz ryzyko), Świadome (robisz to z czystym umysłem) i Za Zgodą (wszyscy się zgadzają).', category: 'BDSM / Kink', examples: ['SSC to klasyczna filozofia — wiele środowisk uzupełnia ją nowszymi podejściami jak RACK.'] },
  { term: 'RACK (Risk-Aware Consensual Kink)', slug: 'rack', definition: 'Nowsza filozofia BDSM. Żadna praktyka nie jest 100% bezpieczna, ale możesz być świadomy ryzyk i zgadzać się na nie. Bardziej realistyczne niż SSC.', category: 'BDSM / Kink', examples: ['RACK pozwala na bardziej zaawansowane praktyki przy pełnej świadomości ryzyka.'] },
  { term: 'Dom / Domina', slug: 'dom-domina', definition: 'Osoba dominująca w D/s relationship. Bierze kontrolę, daje komendy. Dom = mężczyzna dominant, Domme/Domina = kobieta dominant. Warianty: Daddy/Mommy Dom (nurturing), Master/Mistress (strict).', category: 'BDSM / Kink', examples: ['Jako Domme, ona ustala zasady i granice ich sesji.'] },
  { term: 'Sub / Submissive', slug: 'sub', definition: 'Osoba uległa w D/s relationship. Oddaje kontrolę, słucha komend. Bycie submissive to aktywny wybór — wymaga siły i zaufania, nie jest oznaką słabości.', category: 'BDSM / Kink', examples: ['On chętnie przyjmuje rolę suba w ich dynamice — to jego świadomy wybór.'] },
  { term: 'Switch', slug: 'switch', definition: 'Osoba która może być zarówno dominant jak i submissive — w zależności od partnera, nastroju i sytuacji. Z jednym jest Dom, z innym Sub.', category: 'BDSM / Kink', examples: ['Jako switch lubi zarówno dowodzić jak i być prowadzona.'] },
  { term: 'Top / Bottom', slug: 'top-bottom', definition: 'Top = osoba która "robi" coś podczas scene (wiąże, uderza, penetruje). Bottom = osoba której "robi się" (jest wiązana, przyjmuje uderzenia). Różne od Dom/Sub — Top/Bottom to fizyczna rola, nie power exchange.', category: 'BDSM / Kink', examples: ['Można być "service top" — robisz wszystko ale Sub ma kontrolę nad sceną.'] },
  { term: 'Power Exchange', slug: 'power-exchange', definition: 'Przekazanie władzy i kontroli z jednej osoby na drugą. Centrum BDSM. Może trwać tylko podczas scene, w życiu codziennym (24/7) lub Total Power Exchange (TPE).', category: 'BDSM / Kink', examples: ['Power exchange to nie przemoc — to świadome, negocjowane oddanie i przyjęcie władzy.'] },
  { term: 'Scene', slug: 'scene', definition: 'Konkretna sesja BDSM. Ma negocjowany początek, przebieg i koniec. "Mieliśmy wczoraj scene przez 2 godziny — rope bondage i impact play."', category: 'BDSM / Kink', examples: ['Scene zawsze zaczyna się od negocjacji — co będziemy robić, co jest off-limits, jakie safeword.'] },
  { term: 'Aftercare', slug: 'aftercare', definition: 'Opieka i wsparcie po intensywnych aktywnościach BDSM — przytulanie, rozmowa, woda, koc. BDSM może być intensywny fizycznie i emocjonalnie, aftercare pomaga wrócić do "normalności".', category: 'BDSM / Kink', examples: ['Po każdej sesji poświęcamy godzinę na aftercare — przytulanie i rozmowę o tym co przeżyliśmy.'] },
  { term: 'Sub Drop / Dom Drop', slug: 'sub-drop', definition: 'Emocjonalny kryzys po intensywnej scenie. Wynika ze spadku endorfin i adrenaliny. Objawy: smutek, anxiety, poczucie odłączenia, płaczliwość. Lekarstwo: aftercare, bliskość, odpoczynek.', category: 'BDSM / Kink', examples: ['Dzień po intensywnej scene poczułam sub drop — byłam smutna bez powodu. Mój Dom był ze mną.'] },
  { term: 'Subspace', slug: 'subspace', definition: 'Stan głębokiego relaksu i euforii podczas scene. Sub czuje się "high", może być non-verbal, bardzo uległy. Wynika z zalewu endorfin i zaufania. Ważne: Sub w subspace może nie być w stanie używać safeword.', category: 'BDSM / Kink', examples: ['Gdy wchodzi w subspace, Dom musi być extra uważny — ona może nie być w stanie powiedzieć stop.'] },
  { term: 'Negocjacja', slug: 'negocjacja-bdsm', definition: 'Rozmowa przed scene o tym co będziecie robić, jakie są granice, co jest ok a co nie. Must discuss: hard limits, soft limits, safeword, aftercare needs, triggery.', category: 'BDSM / Kink', examples: ['Negocjacja przed scene to obowiązek — bez niej nie zaczynamy.'] },
  { term: 'Hard Limit', slug: 'hard-limit', definition: 'Absolutna granica której przekraczać nie wolno. Non-negotiable. "Anal sex is my hard limit", "No blood play". Nawet Dom musi to uszanować.', category: 'BDSM / Kink', examples: ['Hard limit to nieprzekraczalna linia — nawet w trakcie scene, nawet jeśli sub jest w subspace.'] },
  { term: 'Soft Limit', slug: 'soft-limit', definition: 'Rzecz której zazwyczaj nie robisz, ale może w odpowiednich warunkach, z odpowiednią osobą, po większej ilości rozmów. Granica "może, zależy od kontekstu".', category: 'BDSM / Kink', examples: ['Spanking to mój soft limit — nie z każdym, ale z Tobą, po negocjacji, ok.'] },
  { term: 'Bondage', slug: 'bondage', definition: 'Wiązanie partnera — ograniczanie ruchu. Typy: rope bondage (shibari, kinbaku), kajdanki (cuffs), tape bondage, suspension (wieszanie w powietrzu).', category: 'BDSM / Kink', examples: ['Bondage to nie tylko wiązanie — to zaufanie i estetyka.'] },
  { term: 'Shibari / Kinbaku', slug: 'shibari', definition: 'Japońska sztuka rope bondage. Shibari = dekoracyjna, artystyczna. Kinbaku = erotyczna, celowo krępująca. W Polsce rosnąca scena, warsztaty w większych miastach.', category: 'BDSM / Kink', examples: ['Shibari to sztuka — sesje mogą być artystyczne, bez kontekstu seksualnego.'] },
  { term: 'Impact Play', slug: 'impact-play', definition: 'Uderzanie partnera dla przyjemności/bólu. Spanking, flogging, caning. Narzędzia: ręka, łopatka (paddle), bat (flogger), trzcina (cane). Bezpieczne strefy: pośladki, uda, plecy (NIE głowa, szyja, nerki).', category: 'BDSM / Kink', examples: ['Impact play zaczynamy od lekkiego spanking ręką — potem ewoluujemy w kierunku flogger.'] },
  { term: 'Brat', slug: 'brat', definition: 'Sub który jest playfully defiant — celowo nie słucha żeby dostać "karę" (którą lubi). "Make me", eye rolling, teasing. Brat Tamer to Dom który wie jak sobie z nimi poradzić.', category: 'BDSM / Kink', examples: ['"Nie możesz mi kazać" — klasyczne zachowanie brata. Dom wie, że to zaproszenie.'] },
  { term: 'Collar', slug: 'collar', definition: 'Obroża/naszyjnik noszona przez Sub jako symbol relacji z Domem. Day collar — dyskretna, na co dzień; Play collar — do scene; Permanent collar — symbol długoterminowego zaangażowania (jak obrączka).', category: 'BDSM / Kink', examples: ['Otrzymanie permanent collar to poważny krok w D/s relationship — traktowany jak rytuał zaręczyn.'] },
  { term: 'Dungeon', slug: 'dungeon', definition: 'Przestrzeń wyposażona do BDSM — krzyż św. Andrzeja, ławka do spanking, klatka, punkty zawieszenia. Może być w klubie, prywatna, albo w domu.', category: 'BDSM / Kink', examples: ['W piwnicy mają prawdziwy dungeon z pełnym wyposażeniem.'] },
  { term: 'Munches', slug: 'munches', definition: 'Spotkania społeczne kink community w publicznym miejscu (kawiarnia, restauracja). Vanilla ubrania, zero play, tylko rozmowy i networking. Świetne dla nowych.', category: 'BDSM / Kink', examples: ['Zaczęłam od munchów — poznałam środowisko zanim zdecydowałam się na play party.'] },
  { term: 'Play Party', slug: 'play-party', definition: 'Prywatne wydarzenie gdzie ludzie robią sceny BDSM. Zazwyczaj w dungeonie lub odpowiednio wyposażonej przestrzeni. Zasady: zgoda obowiązkowa, pytaj przed dotknięciem, szanuj safeword.', category: 'BDSM / Kink', examples: ['Play party różni się od lifestyle club — focus jest na BDSM, nie na seks.'] },
  { term: 'Edge Play', slug: 'edge-play', definition: 'Bardzo ryzykowne praktyki — szara strefa między bezpiecznym a niebezpiecznym. Przykłady: breath play (duszenie), knife play, fire play, blood play. Tylko z dużym doświadczeniem i pełnym zaufaniem.', category: 'BDSM / Kink', examples: ['Edge play to nie dla początkujących — wymaga lat doświadczenia i ekstremalnego zaufania.'] },
  { term: 'Primal Play', slug: 'primal-play', definition: 'Surowy, animalistyczny seks i zabawa — polowanie, szarpanie się, gryzienie, drapanie. Role: Predator (poluje) i Prey (ucieka/chowa się).', category: 'BDSM / Kink', examples: ['Primal play to powrót do instynktów — mniej zasad, więcej intuicji i ciała.'] },
  { term: 'CNC (Consensual Non-Consent)', slug: 'cnc', definition: 'Odgrywanie scenariusza non-consent (rape fantasy) z uprzednią negocjacją i pełną zgodą. Fantasy między zgadzającymi się dorosłymi z safeword. Bardzo kontrowersyjne nawet w kink community.', category: 'BDSM / Kink', examples: ['CNC wymaga najdokładniejszej negocjacji ze wszystkich praktyk — co do szczegółu.'] },
  { term: 'Fetysz', slug: 'fetysz', definition: 'Seksualna atrakcja do konkretnego przedmiotu, części ciała lub sytuacji. Przykłady: foot fetish (stopy), latex/leather, pantyhose, smoking. Różni się od kink tym, że jest niezbędny do satysfakcji.', category: 'BDSM / Kink', examples: ['Każdy ma swoje fetysze — ważne żeby je omówić z partnerem.'] },
  { term: 'Pet Play', slug: 'pet-play', definition: 'Role play jako zwierzę. Sub zachowuje się jak pet, Dom jest owner. Puppy play (pies), kitten play (kot), pony play (koń). Może być seksualne lub nie.', category: 'BDSM / Kink', examples: ['Pet play dla wielu jest relaksem i ucieczką od dorosłych obowiązków — nie zawsze chodzi o seks.'] },
  { term: 'Chastity', slug: 'chastity', definition: 'Sub nosi urządzenie czystości (klatka na penisie lub pas cnoty) i nie może mieć orgazmu ani dotykać się bez zgody Doma. Może trwać godziny, dni, tygodnie.', category: 'BDSM / Kink', examples: ['Chastity to długoterminowy power exchange — Dom kontroluje jedną z najbardziej intymnych sfer życia.'] },
  { term: 'Edging', slug: 'edging', definition: 'Doprowadzanie kogoś blisko orgazmu i zatrzymanie. Powtarzanie. Bardzo frustrujące i jednocześnie bardzo przyjemne. Forma orgasm control/denial.', category: 'BDSM / Kink', examples: ['Edging przez godzinę, a potem permission — intensywność orgazmu jest nieporównywalna.'] },
  { term: 'Consent', slug: 'consent', definition: 'Świadoma, entuzjastyczna zgoda wszystkich stron. Musi być: ongoing (sprawdzasz czy dalej ok), odwołalna (zawsze można powiedzieć stop), informed (wiesz na co się zgadzasz), entuzjastyczna ("ok whatever" to za mało).', category: 'BDSM / Kink', examples: ['"Może" to nie jest zgoda. "Tak, chcę tego" — to jest zgoda.'] },

  // === OGÓLNE / LIFESTYLE ===
  { term: 'Vanilla', slug: 'vanilla', definition: '"Zwykły" seks lub osoba nieinteresująca się CNM/BDSM. Nie jest pejoratywne — to po prostu descriptor. "Vanilla club" = zwykły nightclub bez lifestyle.', category: 'Ogólne', examples: ['Nie ma nic złego w vanilla — każdy ma prawo do własnych preferencji.'] },
  { term: 'Play Partner', slug: 'play-partner', definition: 'Osoba z którą masz seks lub aktywności kink, ale bez pełnej relacji romantycznej. Regularni play partnerzy znają swoje granice, są przetestowani, czują się komfortowo.', category: 'Ogólne', examples: ['Mamy kilku play partnerów z którymi spotykamy się na eventach — bez romantycznego zaangażowania.'] },
  { term: 'Coming Out (CNM)', slug: 'coming-out-cnm', definition: 'Mówienie innym że jesteś w CNM/poly relationship. Podobne użycie jak w LGBT+ kontekście. Wiele osób tego nie robi ze względu na pracę, rodzinę lub społeczną stygmę. Twój wybór.', category: 'Ogólne', examples: ['Coming out przed rodziną był trudny, ale uwolniłam się od kłamstw.'] },
  { term: 'Jealousy vs Envy', slug: 'zazdrość-a-zawiść', definition: 'Zazdrość (jealousy) = strach że stracisz coś co masz. Zawiść (envy) = chcesz coś co ktoś inny ma. W CNM zazdrość jest normalna — nie znika magicznie, trzeba się nauczyć z nią pracować.', category: 'Ogólne', examples: ['Zazdrość to sygnał do zbadania własnych potrzeb — nie rozkaz do działania.'] },
  { term: 'Boundaries', slug: 'boundaries', definition: 'Granice — czego TY potrzebujesz żeby czuć się bezpiecznie. "Potrzebuję testów STI co 3 miesiące." Różne od zasad (rules) — boundaries dotyczą Ciebie, nie kontrolują partnera.', category: 'Ogólne', examples: ['Moje boundaries: zawsze zabezpieczenie z nowymi osobami, zawsze wiem gdzie jesteś.'] },
  { term: 'OSO (Other Significant Other)', slug: 'oso', definition: 'Określenie na partnera/partnerkę Twojego partnera/partnerki. Używane w poly community jako neutralne określenie.', category: 'Ogólne', examples: ['Spotkałam OSO mojego chłopaka i od razu przypadłyśmy sobie do gustu.'] },
]

export function getWordOfTheDay() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000)
  return DICTIONARY_TERMS[dayOfYear % DICTIONARY_TERMS.length]
}

export function getTerm(slug) {
  return DICTIONARY_TERMS.find(t => t.slug === slug)
}

export function getTermsByCategory() {
  const cats = {}
  for (const t of DICTIONARY_TERMS) {
    (cats[t.category] ||= []).push(t)
  }
  return cats
}
