/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  corePlugins: { preflight: false }, // keep existing reset in src/index.css
  theme: {
    extend: {
      colors: {
        background: '#121414',
        surface: '#121414',
        'surface-dim': '#121414',
        'surface-container-lowest': '#0c0f0f',
        'surface-container-low': '#1a1c1c',
        'surface-container': '#1e2020',
        'surface-container-high': '#282a2b',
        'surface-container-highest': '#333535',
        'surface-bright': '#38393a',
        'surface-variant': '#333535',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#d0c5af',
        'on-background': '#e2e2e2',
        outline: '#99907c',
        'outline-variant': '#4d4635',
        primary: '#f2ca50',
        'primary-container': '#d4af37',
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        'on-primary': '#3c2f00',
        'on-primary-container': '#554300',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',
        'inverse-primary': '#735c00',
        'surface-tint': '#e9c349',
        secondary: '#c6c4df',
        'secondary-container': '#47475e',
        'on-secondary': '#2f2e44',
        'on-secondary-container': '#b8b6d1',
        tertiary: '#cecbe7',
        'tertiary-container': '#b2b0cb',
        'on-tertiary': '#2f2e43',
        'on-tertiary-container': '#434359',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#2f3131',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        // generic aliases (used by existing nocturne components)
        display: ['"Bodoni Moda"', 'Georgia', 'serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
        // role-based aliases (match Stitch markup: font-display-lg, font-label-caps, …)
        'display-lg': ['"Bodoni Moda"', 'Georgia', 'serif'],
        'display-lg-mobile': ['"Bodoni Moda"', 'Georgia', 'serif'],
        'headline-md': ['"Bodoni Moda"', 'Georgia', 'serif'],
        'headline-sm': ['"Bodoni Moda"', 'Georgia', 'serif'],
        'body-lg': ['"DM Sans"', 'system-ui', 'sans-serif'],
        'body-md': ['"DM Sans"', 'system-ui', 'sans-serif'],
        'label-caps': ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.15em', fontWeight: '700' }],
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: { 'container-max': '1280px' },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
    },
  },
  plugins: [],
}
